### ISSUE TITLE
Export-ConsumptionToBlobStorage fails with 422 WebDirect not supported

### ISSUE THREAD

**Issue by KashifSaadat** [microsoft/finops-toolkit#1005]
## 🐛 Problem

Certain Workbooks such as `Benefits Usage` complain with the error:
```
'where' operator: Failed to resolve table or column expression named 'AzureOptimizationConsumptionV1_CL'...
```

I believe it is related to the `Export-ConsumptionToBlobStorage` job failing, which gives the following in the logs:
```
Error returned by the Generate Cost Details API. Status Code: 422. Message: {"error":{"code":"422","message":"Unsupported request. offer type: WebDirect for get detailed report request is not supported.Unsupported request. offer type: WebDirect for get detailed report request is not supported. (Request ID: b2e660eb-ac7c-44d8-a17c-366ca1671ede)"}}
```

## 👣 Repro steps
1. Go to https://learn.microsoft.com/en-us/rest/api/cost-management/generate-cost-details-report/create-operation?view=rest-cost-management-2023-11-01&tabs=HTTP#code-try-0
2. Enter scope `/subscriptions/<your-sub-id>` (for info, this is a sub with offer ID `MS-AZR-0036P` Azure Sponsorship)
3. Enter body:
```json
{
  "metric": "AmortizedCost",
  "timePeriod": {
    "start": "2024-09-01",
    "end": "2024-09-15"
  }
}
```
5. Submit request and examine response (same as what is returned by manually starting the Runbook).

## 🤔 Expected

Expected the job to succeed, `AzureOptimizationConsumptionV1_CL` to exist and the related Workbooks to render successfully.

I suspect it is related to the type of subscription I have, not sure if there is a way around this?

**Comment by helderpinto** [comment]
Thank you for reporting this issue, @KashifSaadat. 

As documented [here](https://microsoft.github.io/finops-toolkit/optimization-engine/faq), there is full support only for EA, MCA, or MSDN subscriptions. However, this does not mean that other subscription types are not compatible with the consumption exports runbook. We are always looking to expand AOE to new types of subscriptions.

Do you have a single subscription in your environment?

Can you check what is the Azure Offer and Offer ID for your subscription?

![image](https://github.com/user-attachments/assets/5b3a8fe3-3784-4c6e-b10b-d6b8855672ef)

If you can't find the information above, you can also check your Azure Plan here:

![image](https://github.com/user-attachments/assets/b109e5be-df56-4863-a008-8a1ac70f4dc4)

Finally, can you please run the following query in Azure Resource Graph Explorer (Azure Portal) and share the (anonymized) results?

resourcecontainers
| where type == 'microsoft.resources/subscriptions'
| project subscription=name, subscriptionId, locationPlacement=properties.subscriptionPolicies.locationPlacementId, quotaId=properties.subscriptionPolicies.quotaId

**Comment by KashifSaadat** [comment]
Hi @helderpinto, thank you very much for the quick response!

I've deployed the workloads into a Subscription with type `Azure Sponsorship` and Offer ID `MS-AZR-0036P`, so I suspect that is the reason for this particular API call failing. We have multiple subscriptions as shown below:

```csv
"SUBSCRIPTION","SUBSCRIPTIONID","LOCATIONPLACEMENT","QUOTAID"
"Sub1","SUB-ID","Public_2014-09-01","MSDN_2014-09-01"
"Sub2","SUB-ID","Public_2014-09-01","Sponsored_2016-01-01"
"Sub3","SUB-ID","Public_2014-09-01","MSDN_2014-09-01"
"Sub4","SUB-ID","Public_2014-09-01","MSDN_2014-09-01"
"Sub5","SUB-ID","Public_2014-09-01","MSDN_2014-09-01"
"Sub6","SUB-ID","Public_2014-09-01","Sponsored_2016-01-01"
"Sub7","SUB-ID","Public_2014-09-01","Sponsored_2016-01-01"
"Sub8","SUB-ID","Public_2014-09-01","Sponsored_2016-01-01"
"Sub9","SUB-ID","Public_2014-09-01","Sponsored_2016-01-01"
"Sub10","SUB-ID","Public_2014-09-01","Sponsored_2016-01-01"
"Sub11","SUB-ID","Public_2014-09-01","Sponsored_2016-01-01"
"Sub12","SUB-ID","Public_2014-09-01","Sponsored_2016-01-01"
"Sub13","SUB-ID","Public_2014-09-01","Sponsored_2016-01-01"
"Sub14","SUB-ID","Public_2014-09-01","Sponsored_2016-01-01"
"Sub15","SUB-ID","Public_2014-09-01","Sponsored_2016-01-01"
"Sub16","SUB-ID","Public_2014-09-01","Sponsored_2016-01-01"
"Sub17","SUB-ID","Public_2014-09-01","Sponsored_2016-01-01"
"Sub18","SUB-ID","Public_2014-09-01","Sponsored_2016-01-01"
```

Would I need to deploy the stack into a Subscription with the correct agreement type, e.g. `Sub1`?

**Comment by helderpinto** [comment]
Hi, @KashifSaadat. 

Among the list above, only subscriptions with quota ID `MSDN_2014-09-01` are currently supported. So, yes, normally, you should have deployed AOE into one of those subscriptions and grant the Reader role to the AOE managed identity only in the other supported subscriptions as well.

However, if you don't mind, I would like to give a try to a work-around that we never had the chance to test. Around lines 628-629 of the runbook, you find the following instructions:

```powershell
$CostDetailsSupportedQuotaIDs = @('EnterpriseAgreement_2014-09-01','Internal_2014-09-01','CSP_2015-05-01')
$ConsumptionSupportedQuotaIDs = @('PayAsYouGo_2014-09-01','MSDN_2014-09-01')
```

Can you try adding `Sponsored_2016-01-01` to the list of `$ConsumptionSupportedQuotaIDs` and manually run the runbook (no parameters input needed)? Like this:

```powershell
$ConsumptionSupportedQuotaIDs = @('PayAsYouGo_2014-09-01','MSDN_2014-09-01','Sponsored_2016-01-01')
```

**Comment by KashifSaadat** [comment]
Hi @helderpinto,

I've given this a run with the change you've suggested. It allowed the runbook to complete successfully, however I noted the following in the logs output for each subscription: `Generated 0 entries...` (all CSV outputs it mention say a Length of 0 also).

So it looks like although it ran and generated CSVs to upload, none of them have any data (validated this by checking the files in the `consumptionexports` container).

**Comment by helderpinto** [comment]
Unfortunately, @KashifSaadat, it seems the APIs that are being used do not support Sponsorship subscriptions, as it is also documented [here](https://learn.microsoft.com/en-us/rest/api/consumption/#list-of-unsupported-subscription-types). Therefore, you'll have to redeploy AOE in a supported subscription (MSDN).

**Comment by KashifSaadat** [comment]
Ah no worries, thanks for the info. I'll redeploy it in an MSDN subscription. 👍
