### ISSUE TITLE
AOE Jobs fail, missing AzureOptimization_StorageSinkRG variable

### ISSUE THREAD

**Issue by KashifSaadat** [microsoft/finops-toolkit#1012]
## 🐛 Problem

The PR https://github.com/microsoft/finops-toolkit/pull/991 removed the creation of the `AzureOptimization_StorageSinkRG` and `AzureOptimization_StorageSinkSubId` automation variables. Because of this, on a completely fresh deployment every single Export Job that runs now fails.

## 👣 Repro steps

1. Run `.\Deploy-AzureOptimizationEngine.ps1`, deploying a completely new stack into an MSDN Subscription
2. Supply arguments and answer Y to all questions
3. Specify MCA, an active Billing Account ID and Billing Profile when prompted
4. Wait for everything to deploy successfully
5. Grant relevant extra permissions to the Automation Account identity where required (on other Subscriptions)
6. Wait for the first Jobs to run

## 🤔 Expected

The Jobs should all run successfully

## ℹ️ Actual

All jobs have an exception:
```
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Variable not found. To create this Variable, navigate to the Variables blade and create a Variable named: AzureOptimization_StorageSinkRG. Refer doc for more details (https://docs.microsoft.com/en-us/azure/automation/shared-resources/variables#create-and-get-a-variable)
```

**Comment by helderpinto** [comment]
Thanks for reporting this issue, @KashifSaadat. You are deploying AOE from the `dev` branch, which is the default branch for the repository. Unfortunately, the setup script did not account for the possibility of having a `dev`-based deployment that is incompatible with the `main` branch (where the runbooks deployment comes from). In order to work around this problem, can you please re-deploy AOE with the following instruction?

```powershell
./Deploy-AzureOptimizationEngine.ps1 -TemplateUri "https://raw.githubusercontent.com/microsoft/finops-toolkit/refs/heads/dev/src/optimization-engine/azuredeploy.bicep"
```

**Comment by KashifSaadat** [comment]
Aha sorry I missed that, will deploy using the above 👍 Thanks!

**Comment by helderpinto** [comment]
Closing issue, as the 0.6 toolkit release added setup instructions to avoid this type of problem reoccurring.
