### ISSUE TITLE
AOE - Workbook | Savings Plans Usage - Errors in tabs

### ISSUE THREAD

**Issue by psilantropy** [microsoft/finops-toolkit#1026]
## 🐛 Problem
Workbook | Savings Plans Usage reports 2 errors in 2 tabs.

- Full Usage Report

`'project' operator: Failed to resolve scalar expression named 'ExpiryDate_t'...`

- Unused Savings Plan Analysis - Used Savings Plan Details

`'project' operator: Failed to resolve scalar expression named 'ExpiryDate_t'...`

## 📷 Screenshots

![example](https://github.com/user-attachments/assets/2f2d4697-8e93-4e14-a4d7-6c06741dae6c)

## ℹ️ Additional context

- EA Customer
- Single Savings Plan
- Savings Plan in **Expiring** State

**Comment by helderpinto** [comment]
Thanks for reporting this issue, @psilantropy. There seems to be a schema difference between EA/MCA savings plans API responses. We will investigate a solution to normalize both and hopefully share a tentative fix soon.

Tagging @flanakin for awareness.

**Comment by helderpinto** [comment]
Hi, @psilantropy. 

There is a PR ([#1047](https://github.com/microsoft/finops-toolkit/pull/1047)) that will fix this issue. If you want to try out the fix before the release, you just have to make sure you are running AOE on the latest version (September release) and then update the `Export-SavingsPlansUsageToBlobStorage` runbook with [this code](https://github.com/microsoft/finops-toolkit/blob/740790007ac8e3bacf13fa1d6441d82213ee8b8a/src/optimization-engine/runbooks/data-collection/Export-SavingsPlansUsageToBlobStorage.ps1). After the next Savings Plans export+ingest cycle, the Savings Plans workbook should load correctly.

If you are not on the latest AOE release, check [here](https://microsoft.github.io/finops-toolkit/optimization-engine/setup-options#-upgrading-aoe) how to upgrade.

**Comment by psilantropy** [comment]
Thanks. Updated just now, but missed the job by 30 minutes. I will let it run as per schedule and give you an update tomorrow.
Appreciate it :)

**Comment by psilantropy** [comment]
Hi, @helderpinto  - This ended up generating an error. (I am on the latest AOE)
Last stage of runbook was `Uploading CSV to Storage`

`The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: This request is not authorized to perform this operation using this permission. HTTP Status Code: 403 - HTTP Error Message: This request is not authorized to perform this operation using this permission. ErrorCode: AuthorizationPermissionMismatch ErrorMessage: This request is not authorized to perform this operation using this permission. RequestId:xxxxxxx`

![image](https://github.com/user-attachments/assets/0e997868-35bf-41b6-b92f-4909aa7996d1)

Just doing a few tests, checking logs now. But not getting much more info so far. Next run-time is in about 5 hours.

**Comment by helderpinto** [comment]
Hi, @psilantropy. As I stated above, before updating the runbook code, you must upgrade AOE to the latest release. Authentication to Storage by the Automation Account identity is now Entra ID-based. The error you got is because the AOE identity does not have the Storage Blob Data Contributor role on the Storage Account.

**Comment by psilantropy** [comment]
Yeah this is the only error I can pull;

```
ErrorCode: AuthorizationPermissionMismatch
ErrorMessage: This request is not authorized to perform this operation using this permission.
```

I was just trying to compare Export-ReservationsPriceToBlobStorage and Export-SavingsPlansUsageToBlobStorage but they seem a little different with how they handle auth/upload.

**Comment by psilantropy** [comment]
> Hi, @psilantropy. As I stated above, before updating the runbook code, you must upgrade AOE to the latest release. Authentication to Storage by the Automation Account identity is now Entra ID-based. The error you got is because the AOE identity does not have the Storage Blob Data Contributor role on the Storage Account.

Sorry I misinterpreted that and thought I was on the latest version. I'll review now and let you know. Thank you.
