### ISSUE TITLE
Azure Opmization Engine: PowerBI report

### ISSUE THREAD

**Issue by guidovanbrakel** [microsoft/finops-toolkit#1053]
Hello @helderpinto 

I need some help with my PowerBI report, I connected my own database but the PowerBI report keeps being empty, please help. Also when I publish it
![Image](https://github.com/user-attachments/assets/9dbadbd1-0e84-4440-b0df-e6678947cdbd)

**Comment by helderpinto** [comment]
Hello, @guidovanbrakel . Have you checked the [troubleshooting steps](https://microsoft.github.io/finops-toolkit/optimization-engine/troubleshooting)? There is a question - "_Why are my Recommendations workbook and Power BI report still empty after deploying AOE?_"  - that addresses your issue.

**Comment by guidovanbrakel** [comment]
> Hello, [@guidovanbrakel](https://github.com/guidovanbrakel) . Have you checked the [troubleshooting steps](https://microsoft.github.io/finops-toolkit/optimization-engine/troubleshooting)? There is a question - "_Why are my Recommendations workbook and Power BI report still empty after deploying AOE?_" - that addresses your issue.

Yes I checked that, all my jobs have completed succesfully, I have checked that. I have seen the FAQ but I still have no data in my powerbi report

**Comment by helderpinto** [comment]
Assuming that you already tried refreshing many times your Power BI report, can you also please check two things:

1. Does the `recommendations` container have blobs newer than 7 days? Do these blobs contain recommendations data in JSON format?
1. What was the log output of the most recent job of the `Ingest-RecommendationsToSQLServer` runbook?

Thanks!

**Comment by helderpinto** [comment]
@guidovanbrakel, just to be sure all checks have passed:

1. Have you have changed the Power BI data source to the SQL Database endpoint of your AOE deployment ([see instructions](https://microsoft.github.io/finops-toolkit/optimization-engine/reports))?
1. Has Azure Advisor been reporting recommendations for the subscriptions in the AOE scope?
1. Have you refreshed the Power BI report?
1. Can you find recent files (newer than 7 days) in the `recommendationsexports` container in the AOE storage account? Do these files contain recommendations or are they empty?

**Comment by helderpinto** [comment]
@guidovanbrakel, is there any update from your end regarding this issue? Thanks.

**Comment by helderpinto** [comment]
@guidovanbrakel, given there hasn't been any further feedback over the past weeks, we are closing this issue. Feel free to reopen it in case the problem you described reoccurs. Thank you.
