### ISSUE TITLE
[Documentation] Storage Blob Data Reader Role Required to Resolve `Access to the resource is forbidden` Error

### ISSUE THREAD

**Issue by AErmie** [microsoft/finops-toolkit#1069]
## ⚠️ Problem
When using the PowerBI reports with the Hub architecture, encountered the following error: `Error: Access to the resource is forbidden.` This was for the following tables:
- HubScopes
- HubSettings
- SqlDatabases

![Image](https://github.com/user-attachments/assets/c5b5921f-4471-4dd5-a61a-e2d9af7c0c36)

## 🛠️ Solution
Based on the following closed GitHub Issues ([Error to Connect the report](https://github.com/microsoft/finops-toolkit/issues/693), and [Access to the resource is forbidden when connecting to stroage account with powerBI](https://github.com/microsoft/finops-toolkit/issues/708)), the **[Storage Blob Data Reader](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles/storage#storage-blob-data-reader)** role is required, _even if_ you're a Reader, Contributor, or Owner on the storage account.

The following documentation was reference ([Hubs - Required Permissions](https://microsoft.github.io/finops-toolkit/hubs#-required-permissions)), but this only mentions the [Cost Management Reader](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles/management-and-governance#cost-management-reader) role. That role does not include the required `Microsoft.Storage/storageAccounts/blobServices/containers/blobs/read` dataActions permissions needed.

Please update the documentation to clearly indicate that **Storage Blob Data Reader** is required above and beyond even Reader, Contributor, or Owner on the storage account.

## ℹ️ Additional context
Granting the Storage Blob Data Reader permissions on the Storage Account resolved my `Access to the resource is forbidden` errors.

## 🙋‍♀️ Ask for the community
We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by flanakin** [comment]
@AErmie Sorry for the confusion. The first paragraph in that section points to the [template details page](https://microsoft.github.io/finops-toolkit/hubs/template#-prerequisites) which has all the required permissions. We'll bring those into the main doc to make this clearer.

**Comment by ro100e** [comment]
Required permissions have been brought to the main doc in pr #1179
