### ISSUE TITLE
FinOps hub deployment error / AzDataFactory Trigger script failure - Invalid Time Zone

### ISSUE THREAD

**Issue by ablanken** [microsoft/finops-toolkit#1085]
## 🐛 Problem
The FinOps hub deployment to Azure using the template fails when deploying to Australia East.

## 👣 Repro steps
Deploy the FinOps hub to Azure using the Azure Commercial template button @ https://microsoft.github.io/finops-toolkit/help/deploy. Set the location to Australia East.

## 🤔 Expected
No errors reported.

## 📷 Screenshots

![Image](https://github.com/user-attachments/assets/efd0ee90-0bfe-427d-942a-e972d1608f78)

`Executing script: .\userscript.ps1 
Starting trigger msexports_FileAdded...
WARNING: You're using Az version 8.0.0. The latest version of Az is 12.4.0. Upgrade your Az modules using the following commands:
  Update-Module Az -WhatIf    -- Simulate updating your Az modules.
  Update-Module Az            -- Update your Az modules.
There will be breaking changes from 8.0.0 to 12.4.0. Open https://go.microsoft.com/fwlink/?linkid=2241373 and check the details.
done...
Starting trigger config_SettingsUpdated...
done...
Starting trigger config_DailySchedule...
Start-AzDataFactoryV2Trigger: /mnt/azscripts/azscriptinput/userscript.ps1:29
Line |
  29 |          $triggerOutput = Start-AzDataFactoryV2Trigger
     |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | HTTP Status Code: BadRequest Error Code: BadRequest Error Message:
     **| ErrorCode=InvalidWorkflowTriggerRecurrence, ErrorMessage=The recurrence
     | of trigger has an invalid time zone 'Australian Eastern Standard Time'.**
     | Request Id: cc0f0914-eefa-48ad-a3b7-bd555f5efdf7 Timestamp
     | (Utc):11/03/2024 22:35:20

failed...
Starting trigger config_MonthlySchedule...
Start-AzDataFactoryV2Trigger: /mnt/azscripts/azscriptinput/userscript.ps1:29
Line |
  29 |         $triggerOutput = Start-AzDataFactoryV2Trigger `
     |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | HTTP Status Code: BadRequest Error Code: BadRequest Error Message:
     **| ErrorCode=InvalidWorkflowTriggerRecurrence, ErrorMessage=The recurrence
     | of trigger has an invalid time zone 'Australian Eastern Standard Time'.**
     | Request Id: 84e3e79f-7559-4242-8ad0-aae095ff6030 Timestamp
     | (Utc):11/03/2024 22:35:21`

**Comment by flanakin** [comment]
@MSBrett is this tied to the time zones you added in bicep?

**Comment by psilantropy** [comment]
I have this same issue coming from v5  if you need any additional information or troubleshooting. But I think i'll have to make another issue for other problems on this upgrade. Thanks :)

`ErrorCode=InvalidWorkflowTriggerRecurrence, ErrorMessage=The recurrence of trigger has an invalid time zone 'Australian Eastern Standard Time'`

**Comment by MSBrett** [comment]
Fixed in #1182
