### ISSUE TITLE
Dashboard loading problems

### ISSUE THREAD

**Issue by VMonfreda** [microsoft/finops-toolkit#1089]
## 🐛 Problem
We find it very difficult to visualize the costs as the program is constantly loading

## 👣 Repro steps
TODO: Add repro steps below:
1. Go to power bi
2. Click on trasform data
3. Scroll down to close and apply
4. See error load dashboard

## 🤔 Expected
I expect to display dashboards quickly and correctly

## 📷 Screenshots
![Image](https://github.com/user-attachments/assets/c517a5f1-50fd-44e6-bc33-0cf9be8aefec)

**Comment by robbdi** [comment]
Which report are you using and how far back did you set the report to query?

**Comment by VMonfreda** [comment]
I'm using the Cost Summary Report.

These are the query configuration:

***@***.***

**Comment by flanakin** [comment]
Loading data from storage and normalizing it to address data versions and cross-channel issues is known to be slow. We're planning to ship and updated version of hubs that works with Azure Data Explorer, which significantly improves the performance. Stay tuned...

**Comment by flanakin** [comment]
We just release 0.7 with support for Azure Data Explorer. Please give that a shot and let us know if you run into any issues. We'll close this for now. Please don't hesitate to open a new issue if needed.

**Comment by VMonfreda** [comment]
Good afternoon,

are there any updates regarding the request? We need to implement a hub for centralized management of Azure cloud costs, but we haven't received any further information.

Could you provide support?

Regards,
V.M.



***@***.***

Valentino Monfreda
CLOUD COMPETENCE CENTER ENGINEER

Via Gaetano De Castillia 6A, 20124 Milan, Italy
Mobile +39 3316271087
***@***.******@***.***>

**Comment by flanakin** [comment]
@VMonfreda This was resolved in November with the release of FinOps hubs 0.7 with Data Explorer support. Please re-deploy the latest version of hubs with Data Explorer or Fabric. Unfortunately, there's not much we can do to optimize performance between Power BI and storage. Data Explorer is recommended or anyone monitoring over $100K in spend with a cost of 0.02% or less, depending on how much you're monitoring. With Data Explorer, reports load within seconds.
