### ISSUE TITLE
Runbook Export-PriceSheetToBlobStorage generates a CSV that contains only column headings

### ISSUE THREAD

**Issue by Paperiris** [microsoft/finops-toolkit#1099]
I have installed the Optimization Engine and configured the Managed Identity to have access to the Enterprise Agreement.

![Image](https://github.com/user-attachments/assets/56da6226-ac7a-4221-9f85-0a711a450ba9)

### 🐛 Problem
When running the Export-PriceSheetToBlobStorage job, it completes successfully and generates a CSV to the Storage Account.  However the CSV only contains the column headings and no other information.

### 👣 Repro steps
I go to the Automation Account, select the Job named 'Export-PriceSheetToBlobStorage' and leave all values empty when prompted.  The job runs and completes successfully after around 5 minutes.

![Image](https://github.com/user-attachments/assets/71c5b9d1-1b0e-49c2-adeb-039ef660a022)

When browsing to the CSV in the Storage Account it has a size of 155 bytes and when opened contains only the column headings.

![Image](https://github.com/user-attachments/assets/eb2fa766-1b98-49dd-8896-c6aba7d073f3)

![Image](https://github.com/user-attachments/assets/ac686a75-e1a4-4b00-acb6-91c34fe45529)

### 🤔 Expected
Price Sheet information to be populated in the CSV file

### ℹ️ Additional context

This is an Enterprise Agreement with 30+ subscriptions
As far as I can tell, all necessary permissions have been assigned to the Automation Account Managed Identity (Reader at Root MG, Enrollment Reader, Bill Reader, Global Reader in AAD)
I have reviewed issues #842 and #995 however am still facing the issue

**Comment by helderpinto** [comment]
Thank you for reporting this issue and for all the details, @Paperiris. The reason you're getting no data is because you configured region filters with the Azure Resource Manager format, i.e., `australiaeast,australiasoutheast`. You have to use the pricesheet format instead, which should be `AU East,AU Southeast`.

**Comment by Paperiris** [comment]
Thank @helderpinto, that has fixed the issue and I've successfully generated the price sheet CSV.  Thanks for such a quick response, much appreciated.
