### ISSUE TITLE
[Hubs] New FOCUS 1.0r2 dataset version

### ISSUE THREAD

**Issue by flanakin** [microsoft/finops-toolkit#1112]
## ⚠️ Problem
Reported externally:

> My ADF job is getting failed with below error message
>
> _Operation on target For Each Blob failed: Activity failed because an inner activity failed; Inner activity name: Execute, Error: Operation on target Failed to Load Schema failed: Unable to load the focuscost_1.0r2.json schema file. Please confirm the schema and version are supported for FinOps hubs ingestion. Unsupported files will remain in the msexports container._

**Cause:**
Cost Management shipped a new FOCUS dataset version to account for a very minor breaking change in the dataset (dates now have seconds which is required for SQL database ingestion). If the user selects `1.0r2` instead of a supported version, then the error will happen during ingestion.

## 🛠️ Solution
There are 3 options:
1. Update to 0.7 (when released), which will support FOCUS 1.0r2. (This change has already been committed.)
2. Create a new export using FOCUS 1.0.
3. Upload a new schema mapping file for 1.0r2:
   1. Go to **config/schemas** in storage
   2. Download the **focuscost_1.0.json** file
   3. Rename the downloaded file to **focuscost_1.0r2.json**
   4. Upload the renamed file
   5. Rerun the failed pipelines in ADF

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by bhaskarsingh84** [comment]
thank you @flanakin it did help me to fix my broken one.
