### ISSUE TITLE
[Documentation Improvement] Convert Cost Management data to FOCUS

### ISSUE THREAD

**Issue by brianwyka** [microsoft/finops-toolkit#1125]
## ⚠️ Problem
Today, the [Convert Cost Management data to FOCUS](https://microsoft.github.io/finops-toolkit/focus/convert) documentation for performing transformation is not 100% clear for  cost related columns.

`BilledCost` and `EffectiveCost` reference this footnote:
> 1. BilledCost should copy cost from all rows except commitment usage that has a PricingModel of “Reservation” or “SavingsPlan” which should be 0. EffectiveCost should copy cost from all amortized dataset rows; commitment purchases and refunds from the actual cost dataset should be 0.

I understand this as the following for `BilledCost`, but not sure if its correct.
```
IF (PricingModel = 'Reseration` OR PricingModel = 'SavingsPlan') {
  0
} else {
 CostInBillingCurrency
}
```
However, `EffectiveCost` does not give actual values that should be checked for proper calculation.  What is the criteria for knowing a row is amortized and if the row is "commitment purchase or refund"?

`ContractedCost` has the column as `UnitPrice * Quantity` and a description of a lookup required against the `PricingUnits` reference data.

> Map UnitOfMeasure using [Pricing units data file](https://microsoft.github.io/finops-toolkit/data#-pricing-units) and divide Quantity by the PricingBlockSize

Is the proper equation `UnitPrice * (Quantity / PricingBlockSize)`?

## 🛠️ Solution
Please clearly document the conversion of `CostInBillingCurrency` for `BilledCost`, `EffectiveCost` and `ContractedCost` so there is no guessing in how this is done.

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by flanakin** [comment]
We can clarify this. Your logic is correct for `BilledCost`.

As a starting point, you should copy all rows from the amortized cost dataset and only the commitment purchases and refunds from the actual cost dataset. To identify commitment discount purchases and refunds, look for ChargeType == "Purchase" and PricingModel == "Reservation" or "SavingsPlan".

For `ContractedCost`, your formula is also correct.

**Comment by flanakin** [comment]
@brianwyka Would you mind taking a look at PR #1153 to see if that helps?

**Comment by brianwyka** [comment]
Thanks @flanakin .  I'll take a look at it today!  

If I understand correctly, I need both the `Cost and usage details (actual)` and `Cost and usage details (amortized)` to correctly calculate those cost fields. 

Is there any alternative with just the actual cost data?  If we only have the actual, can we only safely calculate `ContractedCost` and `LiatCost`?

**Comment by flanakin** [comment]
> If I understand correctly, I need both the Cost and usage details (actual) and Cost and usage details (amortized) to correctly calculate BilledCost and EffectiveCost fields.

Correct.

> Is there any alternative with just the actual cost data? If we only have the actual, can we only safely calculate ContractedCost and LiatCost?

If you don't have any commitment discounts, then using actual cost alone is fine. If you do have commitment discounts, then you won't be able to show an accurate `EffectiveCost` value.

**Comment by flanakin** [comment]
Btw, thanks for the review! I love your comments and depth in reviewing this! So awesome to see from the community! 😊

I responded to your comments with some additional suggestions. Take a look and let me know if it'd be better to walk thru this in a call. Happy to find some time.
