### ISSUE TITLE
FOCUS 1.0r2 export not being processed.

### ISSUE THREAD

**Issue by lundejd** [microsoft/finops-toolkit#1152]
I set up a new export and didn't watch closely at the FOCUS version only to realize there is a new default "1.0r2" that cannot be processed by the FinOps toolkit. 

![Image](https://github.com/user-attachments/assets/b816101e-d30b-4011-aca6-14d8d0210ece)
![Image](https://github.com/user-attachments/assets/2117f727-152a-452c-8161-f22e9fac951e)

So for those setting up a new export, be sure to stick with the 1.0 release for now.

**Comment by flanakin** [comment]
See #1112

Refer to option 3 in the additional context section for a simple workaround you can use today.
