### ISSUE TITLE
PowerBI Report Templates missing from 0.7 downloads

### ISSUE THREAD

**Issue by EQ-GALLI** [microsoft/finops-toolkit#1190]
The template PBIX files seem to be missing from 0.7 version download folder.

I have checked these files, and they are available for 0.6 from the download folder for that version.

Also, the download button for the PowerBI report templates, on each of the Toolkit pages (e.g. https://microsoft.github.io/finops-toolkit/power-bi/cost-summary) points to https://github.com/microsoft/finops-toolkit/releases/tag/v0.7, not the download folder, as with the previous versions.

**Comment by lundejd** [comment]
Many have been asking this over on the discussions. I'm completely stuck with a .7 deployment I cannot use because the .6 .pbix file I have isn't working with .7 

I now know better than to touch these upgrades for at least a month.

**Comment by flanakin** [comment]
We updated the release details to call this out explicitly. Thanks, @lundejd!
