### ISSUE TITLE
Azure CSP Cost Export - billingPeriodEndDate & billingPeriodStartDate are null

### ISSUE THREAD

**Issue by mlohmeijer** [microsoft/finops-toolkit#1203]
Hello, 

## 🐛 Problem
In the daily Cost Export made from an Azure Plan subscription the billingPeriodEndDate & billingPeriodStartDate are nulled. 

In the FOCUS (v1.0 - **please make this v1.1**) version of this same export the corresponding fields (BillingPeriodEnd& BillingPeriodStart) are filled so it seems that there is a bug in the standard daily cost export. 

## 👣 Repro steps
In the case of CSP / Azure Plan the export has to be made from each subscription separately so if via the Azure Portal the workflow is:
1. go to cost analysis
2. select download
3. go to "view all exports" 
4. create export "Cost and usage details (actual)", the dataset version is hard locked to 2021-10-01

## 🤔 Expected
It was already known that the data format of this export deviates from what you get from an EA subscription (but if that could be fixed too, that would be fantastic.) 
Expected result is that billingPeriodEndDate & billingPeriodStartDate are filled with the correct dates. 

## 🙋‍♀️ Ask for the community
As more and more customers are being pushed towards the CSP model (Microsoft PR towards any company under 3000 FTE is focused on CSP when their (Cloud) EA expires) this will become a bigger issue. The push to CSP reduces end-user FinOps capabilities and for the CSPs there is limited incentive to assist their customers with this as it eats into their partner earned credits.  

Please upvote to make sure that this gets attention because for independent or in-house FinOps practitioners the CSP model is not an improvement.

**Comment by flanakin** [comment]
Please file this as a support request against Cost Management. I will pass it on, but a support request can be escalated to the engineering team.

The reason FOCUS has these values is because there are additional transforms on top of the actual/amortized data that populates missing BillingPeriodStart/End dates based on the ChargePeriodStart date.

**Comment by mlohmeijer** [comment]
Ticket submitted through the CSP. Thanks for the guidance.
