### ISSUE TITLE
PBIX Reports are not found

### ISSUE THREAD

**Issue by lkshck** [microsoft/finops-toolkit#195]
Hey, there are several references to the PBIX files for CostSummary and CommittedDiscounts, but they're not available in the Repo. Where can I find them?

Error I got:
The main branch of finops-toolkit does not contain the path src/templates/finops-hub/reports/CostSummary.pbix.

Thanks in advance!

**Comment by flanakin** [comment]
You can find PBIX files in the release: https://github.com/microsoft/finops-toolkit/releases/tag/v0.0.1. I'll update documentation to be more explicit. Thank you for reporting!

**Comment by lkshck** [comment]
@flanakin perfect, thank you!

**Comment by flanakin** [comment]
@all-contributors please add lkshck for bug reports
