### ISSUE TITLE
Incorrect Info on SQL AHB

### ISSUE THREAD

**Issue by jaypee1990** [microsoft/finops-toolkit#234]
## 🐛 Problem
When looking at AHB data for SQL, it shows all the DTU core pricing model resources as enabled but explicitly mark those SQL resources which are eligible but have not enabled AHB.

## 👣 Repro steps
1. Go to workbook, AHB section
2. Click on show SQL DB Info
3. Scroll down to chart showing the seggregation of enabled vs not-enabled resources
4. the data is incorrect for the enabled resources, as it adds the resources which have AHUB enabled as well as those which arent eligible, for e.g. DTU based resources.

## 🤔 Expected
Third option to identify which resources arent eligible. so in total, AHUB Enabled, AHUB Not Enabled and AHUB Not Eligible.

## 📷 Screenshots
<img width="434" alt="Screenshot 2023-08-14 at 10 11 33" src="https://github.com/microsoft/finops-toolkit/assets/98926476/03b6208a-a2ef-4038-9100-0115bd1115f5">

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by flanakin** [comment]
@jaypee1990 Thanks for filing the bug. We'll investigate and get back to you!
