### ISSUE TITLE
[PowerShell] Remove-FinOpsCostExport

### ISSUE THREAD

**Issue by flanakin** [microsoft/finops-toolkit#242]
## 📝 Scenario
As a **FinOps practitioner**, I need to **delete exports** in order to **stop exporting data data I don't need**

## 💎 Solution
Create a **Remove-FinOpsCostExport** command to delete Cost Management exports.

### Synopsis
Deletes a Cost Management export.

### Syntax
```powershell
Remove-FinOpsCostExport `
    [-Name] <string> `
    -Scope <string> `
    [-RemoveData] `
    [-ApiVersion <string>]
```

### Description
The Remove-FinOpsCostExport command deletes a Cost Management export. By default, data will not be removed from the storage account. Use the -RemoveData option to also remove all exported data from the storage account.

### Parameters
Parameter | Description
---|---
`-Name` | Required. Name of the export.
`-Scope` | Required. Resource ID of the scope to export data for.
`-RemoveData` | Optional. Indicates whether previously exported data in the storage account should be removed. Default = false.
`-ApiVersion` | Optional. API version to use when calling the Cost Management Exports API. Default = 2023-03-01.

## ℹ️ Additional info
We're creating a command for Cost Management exports because the Az Cost Management module is outdated with no ETA to update. We need to use direct HTTP [Exports API](https://learn.microsoft.com/rest/api/cost-management/exports) calls.

When executed, this command should:

If `-RemoveData` is specified, delete data from the storage account.

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by Springstone** [comment]
@flanakin For -RemoveData, what do we delete? All the ingestion reports under the scope? I assume so for v0.0.1 as the only sub-folder is "amortizedcost" under each monthly date range. There isn't a link between the name and folder of the reports, you can name the export anything.
