### ISSUE TITLE
[Hubs] Error in finops-hub template when tags been added

### ISSUE THREAD

**Issue by AdamAndersson** [microsoft/finops-toolkit#331]
## 🐛 Problem
When deploying the finops hub using the finops-hub template it gives an error at the "Review+Create" step if tags have been added.

**Error:**
{
  "code": "InvalidTemplate",
  "message": "Deployment template parse failed: 'Error reading string. Unexpected token: StartObject. Path '['Microsoft.DataFactory/factories']'.'."
}

## 👣 Repro steps
TODO: Add repro steps below:
1. Go to: https://aka.ms/finops/hubs/deploy
2. Provide subscription, resource group, location, name and storage redundancy and click **next**
3. Provide one or many tags by adding Name and Value. Leave "Resource" set to "3 selected" and click **Next**
4. See error:

{
  "code": "InvalidTemplate",
  "message": "Deployment template parse failed: 'Error reading string. Unexpected token: StartObject. Path '['Microsoft.DataFactory/factories']'.'."
}

## 🤔 Expected
Expectation is validation to pass and you can go ahead and create the finops hub

## 🙋‍♀️ Ask for the community
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by flanakin** [comment]
Thanks for reporting this! Found the issue. We'll get it fixed for the next release. For the time being, please specify tags post-deployment. Sorry for the inconvenience!

**Comment by flanakin** [comment]
@all-contributors please add AdamAndersson for bug
