### ISSUE TITLE
[Hubs] Link to troubleshooting from Power BI reports

### ISSUE THREAD

**Issue by flanakin** [microsoft/finops-toolkit#398]
## ⚠️ Problem
When someone runs into an issue (like not giving themselves access to storage), they may feel stuck and not know where to get help.

## 🛠️ Solution
Since they are most likely configuring the Power BI report, consider adding info about troubleshooting issues directly in the report.

## ℹ️ Additional context
See https://aka.ms/finops/hubs/troubleshoot

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Where would you look for help after deploying a new hub instance?
3. Leave comments to help us solidify the vision.

**Comment by arthurclares** [comment]
I'm taking this one @flanakin
