### ISSUE TITLE
[Hubs] Document access requirements

### ISSUE THREAD

**Issue by flanakin** [microsoft/finops-toolkit#411]
Hi, I was able to install the hub and we have couple of subscriptions to analyze and was not sure if we have sufficient permissions to get the billing data, I would appreciate if any one can clarify on the pre-requisites for getting the billing data, and what is the minimal steps and permissions needed in order to configure the tool kit and the permissions needed.

_Originally posted by @dillib in https://github.com/microsoft/finops-toolkit/discussions/405_

**Comment by arthurclares** [comment]
@flanakin I can take this one as well.
