### ISSUE TITLE
AHB Workbook Incorrect SQL DB information 

### ISSUE THREAD

**Issue by arjenhuitema** [microsoft/finops-toolkit#450]
## 🐛 Problem
Elastic pool databases dont have the License Type property on the database itself, but rather on the Elastic Pool, as such they show up incorrectly in the result

## 👣 Repro steps

1. Create two SQL DB on two separate Elastic pools
2. Enable AHB on one of the two
3. Review the query results. Both database are reported as AHB Enabled.

## 🤔 Expected
Expect the databases to report their AHB correctly. Also it would be great that the results are divided into 3 categories. Enabled, Disabled and Not Applicable.

## 📷 Screenshots

**Both databases show as enabled:**

![Screenshot showing both databases with AHB enabled](https://github.com/microsoft/finops-toolkit/assets/15944031/b562220d-7e45-41ab-8cc2-ccba1630b25c)

**Pool1 is enabled and Pool 2 is disabled**

![Screenshot showing AHB enabled on Pool1 and disabled on Pool2](https://github.com/microsoft/finops-toolkit/assets/15944031/8efe8ce3-359f-4caf-be2d-1bfd5ca7ea47)

## ℹ️ Additional context

This issue happens because:

1. Elastic pool databases dont have the License Type property on the database itself, but rather on the Elastic Pool
2. The License Type property is passed to a string, in this case the property doesnt exist so it creates an empty string. Later the ```has``` statement in the ```Case``` looks for the value "LicenseIncluded", since both AHB enabled SQL DBs and Elastics DBs show empty values they are marked as AHB enabled.

Example of how the query could look like:

```
Resources
| where type =~ 'microsoft.sql/servers/databases'
| project databaseId = id, databaseName = name, elasticPoolId = tolower(tostring(properties.elasticPoolId)), databaseLicenseType = tostring(properties.licenseType), databaseKind = tostring(kind), subscriptionId
| join kind=leftouter (
    Resources
    | where type =~ 'microsoft.sql/servers/elasticpools'
    | project elasticPoolId = tolower(id), elasticPoolName = name, elasticPoolLicenseType = tostring(properties.licenseType), elasticPoolKind = tostring(kind))
    on elasticPoolId
| project-away elasticPoolId1
| where databaseName != 'master'
| extend AHUBState = case(
['databaseKind'] !has 'vcore' or ['databaseKind'] has 'serverless', "Not Applicable",
['databaseKind'] has 'vcore' and databaseLicenseType has 'LicenseIncluded' or elasticPoolLicenseType has 'LicenseIncluded', "Not Enabled", "Enabled"
)
| summarize count() by subscriptionId, AHUBState
```

![Screenshot showing the results of the query. 1 database with AHB enabled, 1 Disabled and 1 Not Applicable](https://github.com/microsoft/finops-toolkit/assets/15944031/e0fb65c9-9580-4320-9195-45f86b992462)

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
4. Leave comments to help us solidify the vision.

**Comment by arthurclares** [comment]
@sebassem Can you please work on this one? @arjenhuitema Thank you for the code!

**Comment by naseemhira1196** [comment]
Hi, just looking for an update: Were we able to fix this bug?

**Comment by sebassem** [comment]
Yes this was shipped as part of the November release
