### ISSUE TITLE
[Hubs] FinOps Hubs - Ingestion container is empty

### ISSUE THREAD

**Issue by NavidKhan8** [microsoft/finops-toolkit#453]
Encountered issues with both connector solutions:

**Issue1**
Using Cost management app with EA account, after processing almost 20 GB data it failed with below error:

_CostDetails
Failed to save modifications to the server. Error returned: 'There's not enough memory to complete this operation. Please try again later when there may be more memory available. '._

**Issue2**
Able to spin up the FinOps Hubs resources and exported cost management report at MG scope to the hub created storage account under msexports.

ADF pipeline ran automatically and it generated  2 .parquet files under the same storage account but under msexports/amortizedcost container 

Checked the ADF pipeline all the tasks ran successfully.

Tried manually placing these generated .parquet files under ingestion container and opened Focus PowerBI report by updating connector to hub & storage account URL updated with access key but receiving below error

"We cannot convert value null to type Table"

Any pointer will be helpful?

**Comment by NavidKhan8** [comment]
Also to add, after setting the finops hub, after downloading around 2Gb data it returned below error with out of memory error:

CostDetails
Failed to save modifications to the server. Error returned: 'There's not enough memory to complete this operation. Please try again later when there may be more memory available. '.
Query parameters
Storage URL
Failed to save modifications to the server. Error returned: 'There's not enough memory to complete this operation. Please try again later when there may be more memory available. '.
RangeStart
Failed to save modifications to the server. Error returned: 'There's not enough memory to complete this operation. Please try again later when there may be more memory available. '.
RangeEnd
Failed to save modifications to the server. Error returned: 'There's not enough memory to complete this operation. Please try again later when there may be more memory available. '.

**Comment by flanakin** [comment]
> _Failed to save modifications to the server. Error returned: 'There's not enough memory to complete this operation. Please try again later when there may be more memory available.'_

What are you doing when you get this error? Are you refreshing the data, publishing from PBI Desktop to the service, refreshing the data already published to the PBI service, or something else?

> _@flanakin Also to add, after setting the finops hub, after downloading around 2Gb data it returned below error with out of memory error_

Are you using Power BI Pro by any chance? There are known limits to Power BI Pro. I don't know the exact error message or what the limit is, but that's something to check. 

@MSBrett, have you seen this before?

> _ADF pipeline ran automatically and it generated 2 .parquet files under the same storage account but under msexports/amortizedcost container_

This is strange. I haven't heard of this happening before 🤔 What version are you using? The only thing I can think of that might be quirky is the use of management groups. Cost Management exports are very different for management groups. I'm not aware of that causing what you're seeing, tho.


_Sorry for the slow response. I was out last week and am still playing catch-up..._

**Comment by flanakin** [comment]
@NavidKhan8, can you try editing the CostDetails query in Power BI and updating it to `ftk_LoadData(1)`? By default we load actual cost data from the Cost Management connector, which is likely causing this memory issue.

**Comment by flanakin** [comment]
@NavidKhan8 Can you email me at micflan@ms? Let's find some time to walk thru this together.

**Comment by NavidKhan8** [comment]
> @NavidKhan8 Can you email me at micflan@ms? Let's find some time to walk thru this together.

Couldn't decode the domain, is it @microsoft.com? @microsoftopensource.com :) ?

**Comment by flanakin** [comment]
@allcontributors please add @NavidKhan8 for bug

**Comment by flanakin** [comment]
I'm working with Navid to update to FinOps hubs 0.2 from the latest release @ https://aka.ms/ftk/latest.

Will move this to 0.3 while we confirm the fix.

**Comment by flanakin** [comment]
Update: We're currently validating [FinOps hubs 0.2.1-rc2](https://aka.ms/finops/hubs/rc) to address this.
