### ISSUE TITLE
[Hubs][Power BI] CostSummary -> Finops hub connection fails. ftk_LoadData expects DataLake Storage not Blob

### ISSUE THREAD

**Issue by DennisR73** [microsoft/finops-toolkit#472]
## 🐛 Problem
Replacing the StorageUrl parameter in the CostSummary report (v.0.1.1) with the value from the Finops Hub deployment results in error:

```
An error occurred in the ‘ftk_LoadData’ query. DataSource.Error: AzureDataLakeStorage failed to get contents from 'https://finopshubhqluyac2ikl7s.blob.core.windows.net/ingestion'. Status code: 404, description: 'The specified container does not exist.'.
Details:
    DataSourceKind=AzureDataLakeStorage
    DataSourcePath=https://finopshubhqluyac2ikl7s.blob.core.windows.net/ingestion
    Url=https://finopshubhqluyac2ikl7s.blob.core.windows.net/ingestion
```

It seems to expect DataLake storage not Blob. Did I miss something in the documentation  or should this be the way to change the data source?

## 👣 Repro steps
1. Open CostSummary.pbix
2. Transform Data
3. Update Storage Url parameter under Finops hubs[4]
4. Try to refresh CostDetails data set

**Comment by flanakin** [comment]
We definitely expect Azure DataLake Storage Gen2 in Power BI. That said, this can be worked around by switching to the storage connector.

@MSBrett, does Data Factory require ADLS or would blob storage be okay as is?

Did you customize the template to use blob storage? The template should be locked down to only use ADLS today, unless we have a gap.

Out of curiosity, is there a reason you want to use blob storage rather than ADLS? I believe ADLS has perf improvements that will be needed for larger datasets.

**Comment by DennisR73** [comment]
@flanakin, I dont have a preference for Blob. I just followed the [deployment ](https://microsoft.github.io/finops-toolkit/hubs#-create-a-new-hub) of the FInops hub which creates Blob storage.

**Comment by MSBrett** [comment]
Blob will work too.
ADLS was selected because it has some parquet enhancements with respect to server side filtering of data.

Regards,
Brett/
________________________________

**Comment by flanakin** [comment]
@DennisR73 the template should create an ADLS Gen2 storage account. Can you share a screenshot of the parameters used in the template deployment?

You can convert the storage account to Data Lake Gen2 from the storage account by selecting the `Data Lake Gen2 upgrade` menu item for the storage account.

**Comment by flanakin** [comment]
Let us know if you run into this again. Happy to tweak things if there's a way to avoid issues. I'm also happy to add blob support if there's value in that. 

Thanks for circling back! Let us know if you run into any other issues or have any feedback. Would love to know how things are going and how we can improve your experience.
