### ISSUE TITLE
[Workbook] Include RSV queries to check the vault's replication settings

### ISSUE THREAD

**Issue by arthurclares** [microsoft/finops-toolkit#479]
## 📝 Scenario
For the ACOA Cost workbook, instead of having using click on a single recovery services vault to view the replication, you can add the redundancy settings by adding one more property to the extend statement. redundancySettings = tostring(properties.redundancySettings['standardTierStorageRedundancy']) Clicking on a single one has led to confusion with the customer and it is time consuming. This way reduces the complexity of the section by removing the subsequent API call. See example in attachments. Also, I am currently working on a PowerShell script to do all of the exports from the workbook and hopefully all other exports as well (Advisor, Orphan Resources, etc.)

## 💎 Solution

Workaround: Example provided in screenshot. Updated Query KQL below. Resources | where type == 'microsoft.recoveryservices/vaults' | where resourceGroup in ({ResourceGroup}) | extend skuTier = tostring(sku['tier']), skuName = tostring(sku['name']), redundancySettings = tostring(properties.redundancySettings['standardTierStorageRedundancy']) | order by id asc | project subscriptionId, id, resourceGroup, location, skuTier, skuName, name, RGVault = resourceGroup, redundancySettings | join kind = inner ( resources | where type == 'microsoft.recoveryservices/vaults' | where resourceGroup in ({ResourceGroup}) | extend replaced_tags = replace('{}', 'null', tostring(tags)) | extend replaced_tags = parse_json(replaced_tags) | mv-expand replaced_tags | extend tagName = tostring(bag_keys(replaced_tags)[0]) | extend tagValue = tostring(replaced_tags[tagName]) | where tagName has '{TagName}' and tagValue has '{TagValue}' | summarize arg_max(tagName, tagValue) by id ) on id | extend resourceGroup = tostring(split(id,'/providers/')[0]) | project-away id1

## ℹ️ Additional context
![image](https://github.com/microsoft/finops-toolkit/assets/53261392/c024e933-21ec-40f7-bef4-40adf93c437d)

This feedback was manually moved from the VBD feedback to FinOps toolkit.

Requestor: mikeo
Role: CSA
Location: US

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by arthurclares** [comment]
@sebassem I gave this one to you as you have a similar feedback item that you are working on. We need to validate the code, though.

**Comment by sebassem** [comment]
It seems this has been added recently to azure resource graph, will add it in the December's release
