### ISSUE TITLE
AHUB results are completely inaccurate. 

### ISSUE THREAD

**Issue by naseemhira1196** [microsoft/finops-toolkit#483]
## 🐛 Problem
TODO: We ran the workbook multiple times in the customer tenant and my own tenant. The AHUB shows AHUB enabled for VMs but when we look into the portal - it is not actually enabled.

## 👣 Repro steps
TODO: Add repro steps below:
1. Go to Cost optimization assessment workbook.
2. Click on Azure Hybrid Benefit > SQL DB
3. Scroll down to AHUB enabled
4. Click on the server, scroll to configure, and check if the AHUB switch is turned on.

## 🤔 Expected
TODO: Show AHUB enabled accurately

## 📷 Screenshots
TODO:
![AHUBErrorWorkbook](https://github.com/microsoft/finops-toolkit/assets/127528812/9b36dd3c-fce4-4b6f-bd8d-447aa6fc222b)

## ℹ️ Additional context
TODO: Add any other context about the problem here. Remove if not applicable.

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by arthurclares** [comment]
@naseemhira1196 We have submitted a PR with this fix. The ETA for this version to be published is by the 22nd of December.
I will update this thread once again when the change is merged and available in the portal.
Just a heads, the change will be applied to Advisor Cost optimization workbook.
