### ISSUE TITLE
An error occurred in the ‘ftk_LoadData’ query. Expression.Error: The field 'Tags' already exists in the record

### ISSUE THREAD

**Issue by preimerSerrala** [microsoft/finops-toolkit#493]
## 🐛 Problem
When trying to connect via the Cost Management connector Power BI can't load the data with the error:
An error occurred in the ‘ftk_LoadData’ query. Expression.Error: The field 'Tags' already exists in the record
This occurs on the CostSummary report.

## 👣 Repro steps
1. Open the CostSummary Power BI Report
2. Go to Transform data
3. Change the connector to "Cost Management connector" and enter the billing account + billing profile IDs
4. Exit transform data with save and apply

## 🤔 Expected
The data is getting updated from the Azure Cost Management API

Thank you and best regards,

Pascal

**Comment by baptistepa** [comment]
I have the same problem.

An error occurred in the ‘ftk_LoadData’ query. Expression.Error: The field 'Tags' already exists in the record.
Details:
    Name=Tags
    Value=

**Comment by flanakin** [comment]
We've simplified the ftk_LoadData function immensely in 0.2. That should resolve this. I'm going to move this to 0.2.1 as a placeholder so we can confirm it's fixed in the 0.2 release.

**Comment by baptistepa** [comment]
I am getting an error when opening the file...
![image](https://github.com/microsoft/finops-toolkit/assets/104191428/ce93feae-c34e-4c57-9cd8-4d080ab7c87f)

**Comment by p-reimer** [comment]
Dear Michael,

thank you for the update. Unfortunately with the new report the same issue persists with some additional errors when connecting to a MCA account using the manual input scope.

![image](https://github.com/microsoft/finops-toolkit/assets/148454003/27b932d5-3fab-4535-819c-89441903e62a)

**Comment by flanakin** [comment]
@p-reimer Can you email me at micflan@ms? (Spell out the company name + ".com". Hiding from bots.)

**Comment by flanakin** [comment]
> I am getting an error when opening the file... ![image](https://private-user-images.githubusercontent.com/104191428/298061816-ce93feae-c34e-4c57-9cd8-4d080ab7c87f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNzY5NDYsIm5iZiI6MTcwNjE3NjY0NiwicGF0aCI6Ii8xMDQxOTE0MjgvMjk4MDYxODE2LWNlOTNmZWFlLWMzNGUtNGM1Ny05Y2Q4LTRkMDgwYWI3Yzg3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNVQwOTU3MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTdiMDQwZGM2ZmNmZTAwMjM0NjEwMzUzNDBkM2M2MTQ4YTYzZGYwNjY2OWI3MmU0YjE2YjI4MzIyN2EwYmJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zyW22UT3qByyzRGSiwNrS9GTWQTLAryk5WPox6p3OLQ)

@baptistepa, can you confirm which file this was? That setting gets reset every time we open the reports, so it's constantly causing issues and we don't have a way to prevent it or automate the value.

**Comment by flanakin** [comment]
Update: Scheduled a meeting with @preimerSerrala to investigate further.

**Comment by flanakin** [comment]
We noticed the connector for MCA has both a `tags` and a `Tags` column, which is what's causing the issue. As a quick fix, anyone who is running into this can replace lines 3 and 4 in the CostDetails query with:
```
    AmortizedDataset = Table.RemoveColumns({[Key="usagedetailsamortized"]}[Data], {"Tags"}),
    ActualDataset = Table.RemoveColumns(Connector{[Key="usagedetails"]}[Data], {"Tags"}),
```
