### ISSUE TITLE
[Power BI] EA Template app page links to wrong download

### ISSUE THREAD

**Issue by chris-bowman** [microsoft/finops-toolkit#494]
## 🐛 Problem
1. On page [finops-toolkit/power-bi/template-app](https://github.com/microsoft/finops-toolkit/blob/dev/docs/power-bi/template-app.md) the download link points to the wrong PBIX file.
2. The CostManagementTemplateApp.pbix is not included in the release assets.

## 👣 Repro steps
Navigate to the above page, and click download.

## 🤔 Expected
Releases should include the CostManagementTemplateApp.pbix asset, and the download link should download the latest release CostManagementTemplateApp.pbix file.

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by flanakin** [comment]
Oh, man... so glad you got this in... I'm finalizing the 0.1.2 release and forgot about this one! Thanks!

**Comment by flanakin** [comment]
@all-contributors please add @chris-bowman for bug
