### ISSUE TITLE
Cost Optimization Workbook : Storage cost optimization recommendations not available

### ISSUE THREAD

**Issue by bruncili** [microsoft/finops-toolkit#501]
## 🐛 Problem
Advisor - Cost Optimization Workbook - Usage optimization | Storage not loading

## 👣 Repro steps
1. Go to Azure Advisor
2. Click on Workbooks | Cost Optimization |  Usage optimization | Storage
3. Page not loading

## 🤔 Expected
Storage cost optimization recommendations

## 📷 Screenshots
<img width="624" alt="image" src="https://github.com/microsoft/finops-toolkit/assets/72010667/4337df27-2e09-4738-ae56-43224e79e923">

## ℹ️ Additional context
Tested in many tenants

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by bruncili** [comment]
Hi, update: I am a Microsoft FTE, I realized that this bug is not present in the internal Azure Portal (Preview)

**Comment by sebassem** [comment]
@bruncili can you try now. I can see the tab loading correctly.

**Comment by bruncili** [comment]
It works! Thanks a lot.

Bruno Canessa
Cloud Solution Architect
brunocanessa@microsoft.com
