### ISSUE TITLE
An error occurred in the ‘ftk_LoadData’ query. DataFormat.Error: We couldn't parse the input provided as a Date value.

### ISSUE THREAD

**Issue by elvismangarae** [microsoft/finops-toolkit#512]
## 🐛 Problem
When trying to connect via the FinOps hubs data source in CostSummary report, unable to load the data with below error:
An error occurred in the ‘ftk_LoadData’ query. DataFormat.Error: We couldn't parse the input provided as a Date value.

## 👣 Repro steps
1. Create export at subscription scope
2. name export amortizesubscription and run
3. Update CostSummary report with correct storage Url: https://storageexamplename.dfs.core.windows.net/ingestion
4. Apply

## 🤔 Expected
No error, data loads

## 🙋‍♀️ Ask for the community
We could use your help:
1. Please vote this issue up (👍) to prioritize it.
5. Leave comments to help us solidify the vision.

**Comment by erincon01** [comment]
If you change the Date column to date (in lowercase), you will fix the issue. There is no need to comment the code, just change that section.

**Comment by flanakin** [comment]
Thanks for sharing, @erincon01! This has been fixed in 0.2. Stand by for the next release.

**Comment by flanakin** [comment]
@allcontributors please add @elvismangarae for bug

**Comment by flanakin** [comment]
@allcontributors please add @erincon01 for question

**Comment by flanakin** [comment]
This error has been fixed in the 0.2 release. Thanks again for reporting. Please let us know if you run into anything else!

https://aka.ms/ftk/latest
