### ISSUE TITLE
[Power BI] ResourceName not specified for MCA

### ISSUE THREAD

**Issue by flanakin** [microsoft/finops-toolkit#517]
## 🐛 Problem
Reported via email:
> _My customer has MCA subscriptions and is trying to use the PowerBI Cost Management Connector documented at [Connect to Azure Cost Management data in Power BI Desktop. - Power BI | Microsoft Learn](https://learn.microsoft.com/power-bi/connect-data/desktop-connect-azure-cost-management)._
> 
> _They are telling me that the field ResourceName is not coming across like it used to when they had an EA for Azure.  The documentation seems to indicate full parity of tables between MCA/EA now so I am hoping you can point me in the right direction.  The ResourceName field not being present is breaking their reports and causing a lot of frustration.  Anything you can do to help is appreciated._

## 🤔 Expected
ResourceName in cost details should match ARM.

## ℹ️ Additional context
Cost details for MCA doesn’t expose the ResourceName like EA did. As a workaround, we can parse the name out of the ResourceId using something like `SplitColumn()`. 

Example:

```m
Table.SplitColumn(
  Source, 
  "ResourceId", 
  Splitter.SplitTextByEachDelimiter({"/"}, QuoteStyle.Csv, true), 
  {"ResourceId", "ResourceName"}
)
```
 
Cost details fields are documented @ [Understand usage details fields](https://learn.microsoft.com/azure/cost-management-billing/automate/understand-usage-details-fields#list-of-fields-and-descriptions).

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by xavbx33** [comment]
@flanakin please check that it works also with resources like batch as the ResourceId is not ending by the resource name but the PoolName 
for instacnce: 
/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/myRGforBatchAccount/providers/Microsoft.Batch/batchAccounts/myBatchAccount/pools/myPool
in this case the name of the resource is myBatchAccount and not myPool
Probably other type of resources have the same naming convention 

Thank you to pay attention to this specific case
I'm working on another version of the script to extract it
