### ISSUE TITLE
errors loading Power BI

### ISSUE THREAD

**Issue by maikvandergaag** [microsoft/finops-toolkit#519]
## 🐛 Problem
When configuring the Power BI Cost Summary report we receive as many rows loaded as well as errors.

## 👣 Repro steps
1. Open Power BI
2. Create a configuration to the hub
3. Refresh data.

## 🤔 Expected
All rows loaded without errors.

## 📷 Screenshots
![issue display](https://github.com/microsoft/finops-toolkit/assets/9531411/3c1c0d30-45b9-48d7-b016-92648b7f026f)

## ℹ️ Additional context
This was a completely new setup without any customization.

## 🙋‍♀️ Ask for the community
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by flanakin** [comment]
@maikvandergaag, just to confirm, are you using FinOps hubs or the Cost Management connector here? Did you happen to click "View errors" to see what the issue was?

If you're using hubs, we have a big update coming in 0.2 that simplifies a lot of the code and will likely resolve this but it would be helpful to see what the error is.

**Comment by flanakin** [comment]
@allcontributors please add @maikvandergaag for bug

**Comment by maikvandergaag** [comment]
We are using the FinOps Hub. 

Any idea when the 0.2 version is coming?

**Comment by flanakin** [comment]
@maikvandergaag 0.2 is available now @ https://aka.ms/ftk/latest 🙂

Note that 0.2 uses FOCUS exports, so you'll need to recreate exports. You can use PowerShell to create them or a special preview link in the docs: https://aka.ms/exportsv2. 

I'll keep this open and move it to 0.3 for a couple weeks to give you a chance to confirm this works for you.

**Comment by maikvandergaag** [comment]
Thanks, is there any migration path described for moving from 0.1 to 0.2 for the hub and powerbi?

**Comment by flanakin** [comment]
1. Deploy the template (see below)
2. Delete old exports
3. Create new FOCUS exports
4. Backfill data by running exports for previous months
   > _NOTE: There's an **Export selected dates** command in the new export experience that allows picking specific dates without creating separate one-time exports._
5. Download and setup the new Power BI reports
6. Optional: After all is done, if you want to reduce storage costs, delete the old data

FYI - Here's a release candidate that fixes 2 known bugs in 0.2: https://gist.github.com/flanakin/419b5ed778d12a109b297d0dd406c10f
I did a quick pass to make sure the files land in ingestion. Will confirm the rest later.

**Comment by olp0678** [comment]
hey Michael,

We just used the deployment you have in the previous post, we are getting this error when we try to connect to the data source (storage account with parquet files). we are testing trying to ingest to the laste costSummary.pbix and also costSummary.pbit, both with the same error.

screenshot below
![powerBIerror](https://github.com/microsoft/finops-toolkit/assets/54007412/ef23fb2c-3078-4bd8-a55a-3d4eba636098)

**Comment by flanakin** [comment]
@olp0678 There was a path issue in the previous version. I updated that. Please try the latest:

@maikvandergaag, can you also verify this release candidate? We will publish this in the next release soon.

https://finops/hubs/rc

**Comment by olp0678** [comment]
thanks @flanakin , I believe link you have there its not working and you meant this one https://gist.github.com/flanakin/419b5ed778d12a109b297d0dd406c10f , I will deploy and see how it goes.

**Comment by flanakin** [comment]
Doh! I left out the "aka.ms" part. Kinda critical 😅 Fixed the link above.

**Comment by flanakin** [comment]
@maikvandergaag / @olp0678, can y'all confirm whether you're still running into issues? I want to confirm all is good and close this issue.
