### ISSUE TITLE
Scheduled Refresh for PowerBI.com

### ISSUE THREAD

**Issue by maikvandergaag** [microsoft/finops-toolkit#524]
## ⚠️ Problem
At this point, you cannot configure a Scheduled refresh on powerbi.com when using the FinOps Hubs.

As far as I can see and do not see/know a simple location to get this fixed

## 🛠️ Solution
Add load option to the data source to be able to use Scheduled Refresh

## ℹ️ Additional context
For us to work with the reports we would need Scheduled refresh

**Comment by erincon01** [comment]
If you deploy the Power BI report into powerbi.com, you can schedule data refresh (https://learn.microsoft.com/en-us/power-bi/connect-data/refresh-scheduled-refresh). 

If you don't see fresh data into the Power BI, it may be that the data is not moved from the msexport folder to the ingestion folder. If you have .csv files into the msexport folder means that the data is not transferred to the ingestion folder, that is the source for the Power BI.

In my case, the refresh had issues with a column called: BilledCostInUsd that generated errors. I removed that column from the model, and all worked fine.
