### ISSUE TITLE
DeploymentFailed - Documentation to back-out and retry

### ISSUE THREAD

**Issue by psilantropy** [microsoft/finops-toolkit#547]
When completing my first hub deployment today via the template I ran into a few issues.
I couldn't find any 'reverse deployment' or deletion documentation. Is there anything anywhere to detail the procedure?

### Deployment 1
![Resource list 2](https://github.com/microsoft/finops-toolkit/assets/79955883/7c5cf00e-9cba-44bf-8bc1-04b2fac3ce37)

**Failed due to tagging policies.**
**Reason**: Tags specified in the deployment did not reach the storage account, so the deployment failed.
**Backout**: I saw a note somewhere to not redeploy from a failure due to conflict/duplicate, so I deleted all resources in the resource group they deployed to.

### Deployment 2
![Resource list 2](https://github.com/microsoft/finops-toolkit/assets/79955883/0e1d9bb9-9a83-480a-821d-5061c778743c)

**Failure hub:** `The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'. (Code: ResourceDeploymentFailure, Target: /subscriptions/subscription/resourceGroups/resourcegroup/providers/Microsoft.Resources/deployments/storage)`
```
      "code": "RoleAssignmentUpdateNotPermitted",
      "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated."
```

**Reason**: Could be duplication of deployed resources, but I also have a permissions issue I need to resolve `RoleAssignmentUpdateNotPermitted`

### Oops

If it helps, the reason I missed the permissions requirements;

![doc screenshot 1](https://github.com/microsoft/finops-toolkit/assets/79955883/d5c348c1-e602-4517-8c09-53ff4796da47)

Click Deploy
Then went straight to deploy to azure. Didn't know the permissions were in the additional reference to the template.
![doc screenshot 2](https://github.com/microsoft/finops-toolkit/assets/79955883/4f5fa9ac-5b27-45ed-82ca-fde134d75695)

**Comment by psilantropy** [comment]
3rd deployment after deleting resources worked fine.

**Comment by flanakin** [comment]
@psilantropy Sorry for the delay. Missed this one. I'll add docs for backing out. In general, you should be able to just re-deploy. I can't think of a reason off the top of my head that would be a problem with redeploying. ARM is built on the concept of idempotent deployments that can be repeated. This is actually the expected flow based on my understanding.

Worst case, you can delete the RG and try again.

The RoleAssignmentUpdateNotPermitted error is a known one. I've struggled a lot trying to work around that. Very frustrating. Rule of thumb here is don't delete the managed identities. That's where it crops up. If you do, then delete the role assignments. 

I'll make sure this error is added to the troubleshooting guide.

**Comment by psilantropy** [comment]
No need to apologise, thank you. :) I just elevated to ga to sort out any perms problems.
