### ISSUE TITLE
[PowerShell][Hubs] Remove-FinOpsHub fails when there's only one resource

### ISSUE THREAD

**Issue by flanakin** [microsoft/finops-toolkit#554]
## 🐛 Problem
Remove-FinOpsHub fails when there's only one resource:
![Screenshot of a PowerShell error](https://github.com/microsoft/finops-toolkit/assets/399533/e0610722-865a-46ac-b677-24f32f7aa11e)

> ```
> Method invocation failed because [System.Boolean] does not contain a method named 'Reduce'
> ```

## 👣 Repro steps
1. Create a hub
2. Manually delete all resources except for the Data Factory
3. Run `Remove-FinOpsHub` command

## 🤔 Expected
Should return true when successful.

## ℹ️ Additional context
Error is on line 101 of Remove-FinOpsHub.ps1:
```powershell
return ($resources | Remove-AzResource -Force:$Force).Reduce({ $args[0] -and $args[1] }, $true)
```

The fix is to force the `$resources | Remove-AzResource` into an array. We should also be able to simplify and remove the `Reduce()` method.

```powershell
return -not (@($resources | Remove-AzResource -Force:$Force) -contains $false)
```

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by erose96** [comment]
[Reviewing the code](https://github.com/microsoft/finops-toolkit/blob/a4dc87e7c5ba1a1c3ee3ffa3f8b06cb971bdba15/src/powershell/Public/Get-FinOpsHub.ps1#L108), I think the first `if` statement should check for the existence of the `ftk-version` tag and then if it matches across all of the resources it gets applied to, set the value of $version to the tag value.
