### ISSUE TITLE
Error loading FinOps Hubs source in Cost Summary and Committment Discounts reports

### ISSUE THREAD

**Issue by tobiasny** [microsoft/finops-toolkit#559]
## 🐛 Problem
 I followed the deployment guide on the [FinOps Toolkit Documentation page](https://microsoft.github.io/finops-toolkit/hubs#-create-a-new-hub) to deploy my FinOps Hubs resources, and I've set up the FOCUS cost export as suggested. When downloading the Power BI report templates and setting up the Power Query parameter, i.e _storageUrlForPowerBI_, I get an error when trying to refresh the PowerBI datasets.

## 👣 Repro steps
1. Follow the deployment guide on the [FinOps Toolkit Documentation page](https://microsoft.github.io/finops-toolkit/hubs#-create-a-new-hub).
2. Deploy FinOps Hubs using template
3. Setup FOCUS Cost exports for subscription. Called my export **finops-hubs-export**, and connected it to the storage account created by the FinOps Hubs deployment. As a created the FOCUS export for one of my subscriptions, I set the target directory to **subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx**
4. Run export manually to get some initial data
5. When the export has completed, the `msexports_transform` pipeline in the ADF instance is triggered and completes successfully.
6. After successful pipeline run, `ingestion` container in the storage account have been populated with a parquet file containing cost data.
7. Navigating to the FinOps Hubs resource group, then to deployments, and then to the deployment called _hub_. From the outputs pane I retrieve the _storageUrlForPowerBI_ value.
8. Download the **Cost Summary** Power BI report template.
9. Open the Power Query editor to update data source parameter.
10. Press close and apply, which triggers a refresh when redirected back to Power BI desktop.
11. I am prompted with a login-popup, where I enter my organizational account details to authenticate towards the storage account (My organizational account has the Storage Blob Data Contributor Azure RBAC role). After successful login, I press connect.
12. After attempting to refresh the data, the CostDetails dataset fails to refresh with error `We cannot convert the value null to type Table.`

## 🤔 Expected
After completing repro steps 1-12 I would expect the datasets to be refreshed without any errors.

Made some other observations that may imply that there are some bugs in the ADF pipeline or the Power Query functions in the Power BI template.

1. The ADF pipeline activity setting the _metric_ variable sets it to **amortizedcost**, where it should be **focuscost** (but this was easily configurable). See screenshot 1.
2. The ADF pipeline activity setting the _Date_ variable sets it to **name-of-focus-export**, which in turn sets the destination folder path to _ingestion/subscriptions/name-of-focus-export/amortizedcost_. See screenshot 2.
3. Inspecting the _ftk_Hub_ Power Query function, the folder path is parsed to extract both dataset and month, but given the folder structure produced by the ADF extract pipeline, the folder path parsing would yield erroneous results, causing the dataset refresh failure.
4. Inspecting the storage account containers, the cost export produces files in the following directory: _msexports/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/name-of-focus-export/20240101-20240131/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/_.
5. The ADF transform pipeline produce transformed cost data in the following directory: _ingestion/subscriptions/name-of-focus-export/amortizedcost/_.
6. Looking at the code snippet in screenshot 3, the _Dataset_ variable would seem to yield **name-of-focus-export**, whereas the _Month_ variable would seem to yield **amortizedcost**.

### Screenshot 1
![image](https://github.com/microsoft/finops-toolkit/assets/31841479/1f36d4e4-65bd-42c0-91f7-6ecc964b91c5)

### Screenshot 2

![image](https://github.com/microsoft/finops-toolkit/assets/31841479/17c4b762-039b-4783-9f0b-5dadfe96b275)

### Screenshot 3

![image](https://github.com/microsoft/finops-toolkit/assets/31841479/66ba10cc-3125-4919-87db-3d3666afc074)

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
7. Leave comments to help us solidify the vision.

**Comment by tobiasny** [comment]
@flanakin I made the following changes to make the Power BI refresh work:

1. Updated metric variable in ADF pipline activity to be **focuscost**.
2. Updated dynamic expression in ADF pipeline activity that sets the _Date_ variable from `@split(pipeline().parameters.folderName, '/')[sub(length(split(pipeline().parameters.folderName, '/')), 4)]` to `@substring(split(pipeline().parameters.folderName, '/')[sub(length(split(pipeline().parameters.folderName, '/')), 2)], 0, 6)`
3. Updated the _ftk_Hub_ Power Query function in the CostSummary report template. Updated lines 40-45 to 

`    FilterRowsByDate =
        if start = null and end = null then tbl
        else Table.SelectRows(tbl, each
            (start = null or DateTime.From([ChargePeriodEnd]) >= DateTime.From(start))
            and (end = null or DateTime.From([ChargePeriodStart]) < DateTime.From(end))
        ),`

**Comment by psilantropy** [comment]
Same error for me.

Also maybe of note the data source selection is missing the CM connector option. If inserted manually, this results in the same error anyway.

![Data Source](https://github.com/microsoft/finops-toolkit/assets/79955883/24d86a26-bb97-4905-b3d0-08d14ff6c121)

**Comment by flanakin** [comment]
@tobiasny Can you confirm what version of hubs you have deployed? Look in storage at `config/settings.json`. Also, note that after upgrading to hubs 0.2, you'll need to delete the historical data and re-export it using FOCUS. We'll document this upgrade process more clearly...

**Comment by flanakin** [comment]
@psilantropy The connector is not supported in the Cost summary and Commitment discounts reports anymore. We ran into perf issues when trying to do both in the same report, so we split them out to simplify. Use the new [CostManagementConnector.pbix report](https://aka.ms/ftk/pbi).

**Comment by tobiasny** [comment]
@flanakin I can confirm that from the settings.json that I've deployed FinOps Hubs v0.1.2, thanks for clarifying. I used the **Deploy to Azure** button in the documentation, so I guess that link points to the older FinOps Hubs version and not the new one.

**Comment by psilantropy** [comment]
> @psilantropy The connector is not supported in the Cost summary and Commitment discounts reports anymore. We ran into perf issues when trying to do both in the same report, so we split them out to simplify. Use the new [CostManagementConnector.pbix report](https://aka.ms/ftk/pbi).

I was just trying anything.
Same problem as tobiasny anyway. 0.1.2 when I intended to deploy 0.2 but i used the docs and deploy. This might be the source of all issues.

@flanakin You have your Toolkit v0.2 [Latest](https://github.com/microsoft/finops-toolkit/releases/latest) link, then;
New in 0.2, FinOpsHubs. This links you right back to here https://microsoft.github.io/finops-toolkit/hubs where we probably deploy the old version via the deploy button.

Is there an upgrade process or wipe/redo?
