### ISSUE TITLE
Power BI: We cannot convert the value null to type Table.

### ISSUE THREAD

**Issue by robbdi** [microsoft/finops-toolkit#560]
I recently deployed v0.2 of the FinOps hub but I'm receiving an error in Power BI when I use the Cost Summary and Committed Discounts reports:  we cannot convert the value null to type table

![Screenshot 2024-01-24 124534](https://github.com/microsoft/finops-toolkit/assets/16977341/5af65905-7225-47eb-9703-fc7d9379fe77)

I have verified that the user has the recommended permissions, that the exports are successful and I can see the exports in the storage container, and I see content in both the msexports and the ingestion directories. I've verified that the pipeline successfully ran in Azure Data Factory.

**Comment by flanakin** [comment]
@robbdi Did you create new FOCUS exports? 

FinOps hubs 0.2 requires FOCUS exports and won't work with amortized cost exports. We're updating the docs right now to make that more explicit.

**Comment by robbdi** [comment]
![Screenshot 2024-01-29 081429](https://github.com/microsoft/finops-toolkit/assets/16977341/78e146ab-b186-423a-94f2-74f79727c8be)
As you can see in the attached screenshot, I used the FOCUS dataset for the cost management exports.

**Comment by thecloudman** [comment]
Same issue here. Used Focus Exports PBI will not work.

**Comment by secretsoup** [comment]
I'm having the same issue with FOCUS exports only dropping amoritized costs into the ingestion folder.

**Comment by flanakin** [comment]
Are y'all also using the Power BI report from 0.2?

There were 2 bugs in 0.2 -- 3 if you count the ongoing AQT issue. Here's a release candidate that fixes them: https://gist.github.com/flanakin/419b5ed778d12a109b297d0dd406c10f
I did a quick pass to make sure the files land in ingestion. Will confirm the rest later and then publish the release.

@robbdi FYI - If you open the export details, there's an **Export selected dates** command that lets you export one month at a time. That might be simpler than creating one-time exports. I'll document that as well.

**Comment by secretsoup** [comment]
@flanakin Could you advise how to deploy? I get this error:

There was an error downloading the template from URI 'https://gist.github.com/flanakin/419b5ed778d12a109b297d0dd406c10f/raw/bd1bbd8e3a07b09d324ba849bd57a73eca747d14/azuredeploy.json'. Ensure that the template is publicly accessible and that the publisher has enabled CORS policy on the endpoint. 

I tried to deploy by copy/pasting the template into a deployment and it just fails.

**Comment by thecloudman** [comment]
> Are y'all also using the Power BI report from 0.2?
> 
> There were 2 bugs in 0.2 -- 3 if you count the ongoing AQT issue. Here's a release candidate that fixes them: https://gist.github.com/flanakin/419b5ed778d12a109b297d0dd406c10f I did a quick pass to make sure the files land in ingestion. Will confirm the rest later and then publish the release.
> 
> @robbdi FYI - If you open the export details, there's an **Export selected dates** command that lets you export one month at a time. That might be simpler than creating one-time exports. I'll document that as well.

@flanakin I have been able to deploy the rc version by creating a custom template and pasting the code. I created a one-time export from azure portal directly to mspexports container for one month of data. That worked, the data factory pipelines worked and created the right files in the ingestion container. The problem we have now is Power BI, the ftk_hub function is parsing the folder and looking for a date format in the folder path. The exports dont have this it is a guid: 

The error on PBI: 
An error occurred in the ‘’ query. DataFormat.Error: We couldn't parse the input provided as a Date value.
Details:
    c00fc056-8902-436d-b045-cd28542cd59c01

The details show it is trying to read a folder that does not have a date format.

I suspect the parse folder section of ftk_hub is not able to find the specific folder, may need to adjust the code in PBI to find the right folder.

**Comment by flanakin** [comment]
> There was an error downloading the template from URI 'https://gist.github.com/flanakin/419b5ed778d12a109b297d0dd406c10f/raw/bd1bbd8e3a07b09d324ba849bd57a73eca747d14/azuredeploy.json'. Ensure that the template is publicly accessible and that the publisher has enabled CORS policy on the endpoint.

@secretsoup Sorry about that! For some reason the portal can't access a gist 😕 I fixed it. Please try again.

**Comment by flanakin** [comment]
> The problem we have now is Power BI, the ftk_hub function is parsing the folder and looking for a date format in the folder path.

@thecloudman Looks like you deployed rc1, which wasn't putting the data in the ingestion folder correctly. Can you deploy the latest?

https://aka.ms/finops/hubs/rc

**Comment by thecloudman** [comment]
@flanakin attempting to deploy RC2. First deployment failed on storage setting permissions. Doing it again using a new hub name instead of an existing hub name.

**Comment by thecloudman** [comment]
@flanakin RC2 worked. Connected PBI, all seems okay from a connection point of view. Happy to close out this issue. Legend!

**Comment by robbdi** [comment]
I was able to deploy RC2 and it seems to correct the issue with the Cost Summary report. I will try the Commitment Discounts report to see if it's working.

**Comment by flanakin** [comment]
Thanks, all!
