### ISSUE TITLE
Inclusion of a ServiceModel column detailing if the service is IaaS, PaaS etc 

### ISSUE THREAD

**Issue by dflood007** [microsoft/finops-toolkit#567]
## 📝 Scenario
As a FinOps Practitioner I need to split our Azure usage by ServiceModel (PaaS, IaaS, SaaS - not sure if SaaS is relevant within Azure usage??),  in order to produce reports showing for example progress of our journey towards a cloud native setup.

## 💎 Solution
For each line in the FOCUS usage file, add a new Column to reflect whether that line item is IaaS, PaaS, SaaS + there maybe some line items that this type of categorising is not applicable to. After some searching this type of column seems to be widely referred to as the ServiceModel.

## 🙋‍♀️ Ask for the community
I checked with the FinOps community that there is no such mapping already out their, Michael Flanakin confirm there is not and suggested I raise this request.

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by rodneyjoyce** [comment]
While I like the idea of the ability to discern the difference, IMO I don't think this is a FinOps Toolkit issue - it could be raised in the FOCUS spec itself - I think there is value for others across all platforms to be able to distinguish this.

**Comment by flanakin** [comment]
Agreed. The intent of adding this to the toolkit is to give people an option to amend their current data. Most of the open data files we offer in the toolkit are to support FOCUS conversions, so this would be the same.

**Comment by flanakin** [comment]
I talked with a few other toolkit contributors about this and we were debating whether we should split out "Infrastructure" from "as-a-Service" to group on-prem costs. I'm curious what others think. FOCUS will need to get into this, but we can start with just the service model for now. We do need to cover licensing and potentially consulting. 

| Service | Type | Location | ServiceModel |
|---------|-------|----------|----------------|
| Virtual Machines | Infrastructure | Cloud | IaaS |
| Hyper-V VMs | Infrastructure | On-Prem | ??? |
| Microsoft Entra ID | Software | Cloud | SaaS |
| Active Directory | Software | On-Prem | Software |
| Windows Server | Infrastructure? | License? | Software |
| SQL databases | Platform | Cloud | PaaS |
| SQL Server | Platform | On-Prem | Software? |
| Functions | Platform? | Cloud | 
| Consulting | Personnel? | ??? | Personnel? |

FYI - We were also looking at the [Cloud computing article](https://en.wikipedia.org/wiki/Cloud_computing) on Wikipedia.
