### ISSUE TITLE
Incorrect data in the manual updates 

### ISSUE THREAD

**Issue by SamadSaqlain** [microsoft/finops-toolkit#568]
The data is not accurate in the manual update of the FinOps toolkit using the azure data late Gen2.

**Comment by flanakin** [comment]
@SamadSaqlain can you clarify what you're referring to?

We do have a new upgrade guide coming with the 0.2.1. I'd love to know what you're looking for here and we can make sure it's covered as part of that.

**Comment by flanakin** [comment]
@SamadSaqlain Here's a quick upgrade guide I pulled together. Would love your feedback here. We can continue to evolve it based on your feedback.

https://flanakin.github.io/finops-toolkit/hubs/upgrade
