### ISSUE TITLE
Migration FinOps-Hub 0.1 to 0.2

### ISSUE THREAD

**Issue by maikvandergaag** [microsoft/finops-toolkit#569]
Is there an active migration path to move from 0.1 to 0.2 I was not able to find one in the repository.

**Comment by psilantropy** [comment]
Interested too. I currently have an unintended 0.1 deployment. Not sure how to proceed, or if I need to redo all my exports on a new deployment etc.

**Comment by psilantropy** [comment]
https://microsoft.github.io/finops-toolkit/powershell/hubs/Deploy-FinOpsHub

> The Deploy-FinOpsHub command either creates a new or **updates** an existing FinOps hub instance by deploying an Azure Resource Manager deployment template. The [FinOps hub template](https://microsoft.github.io/finops-toolkit/hubs/template) is downloaded from GitHub. To learn more about the template, see the FinOps hub template.

![error](https://github.com/microsoft/finops-toolkit/assets/79955883/e9810a73-f2ed-489c-b915-54ecdfe758c6)

It appears that everything directs you to use the powershell commands to upgrade, but documentation unclear due to typos? I might try anyway.

**Comment by maikvandergaag** [comment]
I tried the template deployment but that one failed for me. That is why I created the issue

**Comment by flanakin** [comment]
I started working on an upgrade doc that should be ready soon. That said, we've identified 2 bugs in FinOps hubs 0.2 that are blocking deployments. Hold off on the upgrade while we get 0.2.1 out to resolve these issues. Apologies for the inconvenience! 😥

**Comment by flanakin** [comment]
PowerShell is not required. The template deployment covers the hubs update. The only special thing in this case is deleting old exports and creating new ones. That said, the 2 bugs are causing a problem that's getting in the way. I'm hoping to have a release out by Monday.

**Comment by flanakin** [comment]
@psilantropy `Deploy-FinOpsHub` can both create a new hub or update an existing one. Thanks for pointing out the inconsistencies! I'll get those fixed in the next update as well.

**Comment by flanakin** [comment]
Update: Here's a release candidate for hubs to address the 2 known bugs in 0.2: https://aka.ms/finops/hubs/rc. Please let me know if you run into any issues with that.

**Comment by psilantropy** [comment]
> Update: Here's a release candidate for hubs to address the 2 known bugs in 0.2: https://aka.ms/finops/hubs/rc. Please let me know if you run into any issues with that. We'll have an official release out soon.

Thanks. I'll give it a try shortly :)

FYI on your deploy to az button;

> There was an error downloading the template from URI 'https://gist.github.com/flanakin/419b5ed778d12a109b297d0dd406c10f/raw/bd1bbd8e3a07b09d324ba849bd57a73eca747d14/azuredeploy.json'. Ensure that the template is publicly accessible and that the publisher has enabled CORS policy on the endpoint. To deploy this template, download the template manually and paste the contents in the 'Build your own template in the editor' option below.

**Comment by flanakin** [comment]
@psilantropy I fixed the Deploy to Azure button. Feel free to try again: https://aka.ms/finops/hubs/rc

**Comment by psilantropy** [comment]
> @psilantropy I fixed the Deploy to Azure button. Feel free to try again: https://aka.ms/finops/hubs/rc

Deployed now. Keen to try the hub based reports. Thank you :)
