### ISSUE TITLE
Deployment failes with status BadRequest on resource keyVault

### ISSUE THREAD

**Issue by DomiOder** [microsoft/finops-toolkit#583]
## 🐛 Problem
During the deployment we receive the following error:
{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The template resource '/add' for type 'Microsoft.KeyVault/vaults/accessPolicies' at line '1' and column '3488' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-syntax-resources for usage details.'.","additionalInfo":[{"type":"TemplateViolation","info":{"lineNumber":1,"linePosition":3488,"path":"properties.template.resources[0].type"}}]}
The ressource displaying this error is the keyVault. The status for all other ressources is successful.

The user has all the necessary permissions acording to the prerequisites.

## 👣 Repro steps
Click the "Deploy to Azure" button on https://microsoft.github.io/finops-toolkit/hubs#-create-a-new-hub

## 🤔 Expected
The deployment should be successful.

## 📷 Screenshots
<img width="924" alt="2024-02-06 14_30_36-hub - Microsoft Azure" src="https://github.com/microsoft/finops-toolkit/assets/47597951/77d77487-656b-4b49-a5f7-7d463fd15621">

## 🙋‍♀️ Ask for the community
We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by erincon01** [comment]
@DomiOder , I had the same issue 2d ago. I believe you are using an older script.
use this https://aka.ms/finops/hubs/rc that I would fix your issue.

**Comment by DomiOder** [comment]
@erincon01 Thank you! That fixed the problem, the deployment was successful now.
