### ISSUE TITLE
Cost Export v2 bug - Date produces export with different date in msexports

### ISSUE THREAD

**Issue by psilantropy** [microsoft/finops-toolkit#584]
NOTE: Exporting a "selected date" from an existing daily export is not  something finopshub directs you to do.
Using this feature on the export is more efficient than creating new exports, so I wanted to see how it looked.

## 🐛 Problem
When completing a daily month to date export, you are able to select "export selected dates" to trigger a date specific export.
When I select the following dates (all November);

![image](https://github.com/microsoft/finops-toolkit/assets/79955883/59ca31f3-f866-4509-a947-5d0633c25042)

I receive this date (all October) in the msexports folder

![image](https://github.com/microsoft/finops-toolkit/assets/79955883/001b8d18-13c3-4a32-b00a-fb3a2b80380b)

Ingestion
![image](https://github.com/microsoft/finops-toolkit/assets/79955883/3d42ba53-455c-4834-be4c-2d1c3e38fb1d)

**Comment by psilantropy** [comment]
Same issue on a standard one-off export using the same 'export selected dates' option. I guess Az has a bug in this method.

**Comment by psilantropy** [comment]
Having fun here. It's just a little buggy overall :>

![image](https://github.com/microsoft/finops-toolkit/assets/79955883/355db9da-6ab5-4fb8-ad76-ddb3df393c16)

I guess March now starts on the 2nd. Problem with Feb only 28 days I guess.

![image](https://github.com/microsoft/finops-toolkit/assets/79955883/a7355e48-b81f-499a-bff5-12e2d65b04e7)

**Comment by psilantropy** [comment]
This 30 day 'period' issue continues into all months;

![image](https://github.com/microsoft/finops-toolkit/assets/79955883/d954257f-dd6d-452a-af36-1f3e2df5ffe7)

**Comment by psilantropy** [comment]
Isolated the bug.

If you edit any existing export v2 job, you cannot select more than 30 days.
If you use a export selected dates in a v2 job, you cannot select more than 30 days.

**Comment by flanakin** [comment]
@psilantropy Thanks for reporting this! Let me share it with the Cost Management Exports team.

**Comment by jojohpm** [comment]
> Isolated another bug while troubleshooting above;
> 
> If you edit any existing export v2 job, you cannot select more than 30 days, even if the month has 31. If you use a _export selected dates_ in a v2 job - same problem.

I was unable to recreate this bug. Export selected dates was allowing me to pick 31 days. Can you please share a screenshot?

**Comment by jojohpm** [comment]
We've filed a ticket to investigate the first issue that you described. Thanks for the feedback.

**Comment by psilantropy** [comment]
> I was unable to recreate this bug with 'Export selected dates'. Can you please share a screenshot?

Hi. Thanks for looking into it :)
The screenshots above are from that issue.

Export selected dates from this;
![input](https://github.com/microsoft/finops-toolkit/assets/79955883/8bcbe3ac-d33b-403f-a8bb-77ab927a0d9c)

Results in this date folder
![output](https://github.com/microsoft/finops-toolkit/assets/79955883/7b66cd50-04f7-4d4a-ba61-d3f14eddd712)

Was there further detail you wanted?

**Comment by jojohpm** [comment]
Thanks for the details. We have filed a ticket to work on this.

**Comment by jojohpm** [comment]
Can you please retry this scenario as the Bug has been fixed?

**Comment by flanakin** [comment]
@psilantropy, give this a try again and let us know if you run into any issues!
