### ISSUE TITLE
Report half-blank - CommitmentDiscounts.pbix - FinOps hubs 0.2.1-rc2

### ISSUE THREAD

**Issue by psilantropy** [microsoft/finops-toolkit#585]
## 🐛 Problem
TODO: After redeploying FinOps hubs 0.2.1-rc2 from [HERE](https://gist.github.com/flanakin/419b5ed778d12a109b297d0dd406c10f).
Then downloading the new CommitmentDiscounts.pbix from [HERE](https://github.com/microsoft/finops-toolkit/releases/tag/v0.2)

I am left with a half-blank report. Only Purchases and Hybrid Benefit have data present. Other tags don't have the subscriptions/services etc.

👣 Repro steps

1: Open CommitmentDiscounts.pbix
2. Enter transform data.
3. Open CM connector: scope (must enter scope here even though I use hub)
4. CM connector: number of months - set to 2.
5. FinOps Hubs - Storage URL - update to my deployment hub output URL.
6. Update Rangestart and range end to 01/12/23 - 31/01/2024
7. CLOSE AND APPLY

All queries loading successfully. No error presented.

Click Commitments, loading icons turn, no data presented. (BLANK)
Cannot select date range in the Commitment tab.

All other tabs up to Purchases are blank.
In purchases I can only select current month. All other days are unselectable.
![image](https://github.com/microsoft/finops-toolkit/assets/79955883/e8f2b09f-a824-41be-a9be-b825a424ca5c)

Go back to Commitments tab, only FROM date is now present. However I can now select any date (even back before my exports are present). This doesn't change the blank data however.

ℹ️ Additional context

If I enter the CostDetails query - I do get data here. A lot of nulls but important items like effective cost, usage quantity are populated.

![image](https://github.com/microsoft/finops-toolkit/assets/79955883/a803c5c5-8451-465a-a46a-bc7e1b00fb46)

RecommendationsSingle - blank
RecommendationsShared - blank
InstantSizeFlexibility - populated ok

**Comment by psilantropy** [comment]
For reference, the CostSummary.pbix report looks ok (I feel some months look wrong, but cannot confirm yet).

Commitments Tab doesn't look great however;
![Commitments](https://github.com/microsoft/finops-toolkit/assets/79955883/a3868518-7d87-4e8d-862b-5d111bb05237)

**Comment by flanakin** [comment]
@psilantropy I was just coming here to file a bug that was reported where the table is empty. There's a `PricingCategory` filter in the Commitment discounts report that was set wrong. The fix is easy. Just edit the filter to filter on `Commitment-Based` instead of `Commitment Discount`.

You'll need to apply it to the following pages:
- Commitments
- Savings
- Chargeback
- Prices

I'm about to submit a PR. I'll associate it with this issue for now but please let me know if that's the issue you're running into.

**Comment by flanakin** [comment]
@allcontributors please add @psilantropy for bug

**Comment by flanakin** [comment]
@all-contributors please add @psilantropy for bug

**Comment by psilantropy** [comment]
> I'm about to submit a PR. I'll associate it with this issue for now but please let me know if that's the issue you're running into.

Sorry was away a few days. Yes that was exactly the issue and your filter change results in data now. Thank you :).

However, now I see the commitments data - Savings plan data results in an incorrect savings calculation.

![image](https://github.com/microsoft/finops-toolkit/assets/79955883/b4f34f79-a8b5-4c69-87fa-2767e88dc942)

This is the same result I get from the [Azure Savings Dashboard](https://techcommunity.microsoft.com/t5/core-infrastructure-and-security/azure-savings-dashboard/ba-p/3816131). So maybe I have something strange going on here.

This issue is in any tab that includes Savings Plan.
