### ISSUE TITLE
Power BI: CommitmentDiscounts.pbix and error i query (Source is [string], expected vaule [integer])

### ISSUE THREAD

**Issue by patkje75** [microsoft/finops-toolkit#594]
I am using FinOps Hub 0.2 Rc2 (v0.2 would give me the error `we cannot convert the value null to type Table.`) and the Power Bi report **CommitmentDiscounts.pbix**
When i fetch data i get this error 
![image](https://github.com/microsoft/finops-toolkit/assets/5085382/8ba44049-daea-4005-b030-4d250bff7330)
The problem are related to the **x_SkuTerm** column
![image](https://github.com/microsoft/finops-toolkit/assets/5085382/1b7a7ec5-72d7-4a7d-aa59-eeb5d244aa02)

The source file contain the value 3years as `string`, but the report expects an `Integer`, I am not very good at Power Bi, but i have replaced the faulty value and tried to load the fixed query into the report, along with the other CostDetails query, it look OK
![image](https://github.com/microsoft/finops-toolkit/assets/5085382/e5965530-6405-4546-b976-b2a5eb8a6c72)
![image](https://github.com/microsoft/finops-toolkit/assets/5085382/746029f1-0d07-466e-b5ff-b2c526a0c04a)
![image](https://github.com/microsoft/finops-toolkit/assets/5085382/04b8d18c-9e89-477a-93f5-a81d033a101d)

However, it doesn't seem to work
![image](https://github.com/microsoft/finops-toolkit/assets/5085382/ed57f7c4-6aab-4ed4-a655-bde37718511f)
I can see the data in the table view.

Maybe this is beacuse my "fix" isn't working.
Could the issue with the incorrect value type be fixed with some conditional statement, translating "3years" to 36 when loading the data?
Maybe 1year needs to be handled as well.

**Comment by flanakin** [comment]
Thanks for reporting this. I discovered the same thing. Turns out Cost Management returns 2 different values for EA and MCA. I'll add this to the 0.2.1 release.

**Comment by flanakin** [comment]
@all-contributors please add @patkje75 for bug

**Comment by flanakin** [comment]
@patkje75 There are 2 fixes you can apply for this:
1. Change the x_SkuTerm type conversion to "text".
2. Convert the string to a number.

For the first, go to Transform data > Setup > Functions > ftk_CostDetails, then right click and select Advanced Editor. Within the editor, locate `{"x_SkuTerm", type number}` and change `number` to `text`. That'll keep the current values.

The second is a more involved change. I'm happy to share the details if you want to apply it. Just let me know. In the meantime, I'll get a PR out to fix this in 0.2.1.

**Comment by patkje75** [comment]
@flanakin Thanks!

The first one worked, the query went fine no errors, however the report looks the same with (Blank) fields.
Please share the details about the second fix when you have the possibility, thanks!

**Comment by arthurclares** [comment]
This is fixed on the newly release version 0.3.
