### ISSUE TITLE
x_CostCenter not populated

### ISSUE THREAD

**Issue by robbdi** [microsoft/finops-toolkit#607]
Where are you getting "x_CostCenter" data? I am unable to find anything in the report.

Within Power BI, I select "Transform data", select the table "CostDetails" and then I scroll over to the far right to find the X_CostCenter column. When I drop down on the column name and select "load more", I am unable to find any Cost Center data.

In the portal, I know I have cost center defined at the subscription level and it's inherited via a policy to resources under each subscription.

Any suggestions?

**Comment by Jshechtman** [comment]
I had a similar issue where only 20% of my cost centers were being populated. I sent an email to exportsready@microsoft.com since they're the team that handle the exports.

**Comment by flanakin** [comment]
We discovered a bug in the FOCUS transform for x_CostCenter. The fix is ready and should be part of the next release. I'll keep this open to track it and update you here when I hear back on the timeline.

**Comment by arthurclares** [comment]
This is fixed on the newly released version 0.3
