### ISSUE TITLE
Cost Optimization Workbook - Azure Firewall - "Is Intrusion Detection enabled" not detecting Deny

### ISSUE THREAD

**Issue by MS-mikeo** [microsoft/finops-toolkit#613]
## 🐛 Problem
In the Cost Optimization Workbook under Usage Optimization -> Networking -> Azure Firewall - "Is Intrusion Detection enabled?" query, it is showing false when IDPS has been set to "Alert and Deny"

## 👣 Repro steps
1. Need a firewall with firewall policy that you can toggle IDPS mode between Disabled/Alert/Alert and Deny
2. Set to Alert and Deny first (which means IDPS is enabled and blocking suspicious traffic
3. Go to Cost Optimization Workbook under Usage Optimization -> Networking -> Azure Firewall - "Is Intrusion Detection enabled?" query
4. It will say False as it is looking for "Alert" in the query

## 🤔 Expected
It should display True when set to Alert and Deny.  However, this one may be better off than just a True/False.  Alerting, while it is utilizing the setting to get started with IDPS is not blocking traffic.  So maybe False when not using with setting and True (Alert) or True (Alert and Deny) for the other 2 options.

## 📷 Screenshots
![image](https://github.com/microsoft/finops-toolkit/assets/130005316/09c36dd2-068a-4e30-b673-a736a9bc6e04)

![image](https://github.com/microsoft/finops-toolkit/assets/130005316/6233728c-2896-4018-8c5a-713c20ca46a3)

![image](https://github.com/microsoft/finops-toolkit/assets/130005316/9fc5f7da-c500-4fc4-8291-ccad2e432e78)

## ℹ️ Additional context
Fix would be to add an -or with Deny, see below.  Tested in last screenshot above, however this is not an environment where I have write access to test the firewall with both Alert and Alert and Deny.

resources 
| where type =~ 'Microsoft.Network/azureFirewalls'
| project FWID=id, firewallName = name, SkuTier = tostring(properties.sku.tier), resourceGroup, location
| join kind=inner (
    resources
    | where type =~ 'microsoft.network/firewallpolicies'
    | mv-expand properties.firewalls
    | extend intrusionDetection = tostring(properties.intrusionDetection contains "Deny" or properties.intrusionDetection contains "Alert"), transportSecurity = tostring(properties.transportSecurity contains "keyVaultSecretId")
    | extend FWID=tostring(properties_firewalls.id)
    | project PolicyName = name, PolicySKU=tostring(properties.sku.tier), intrusionDetection, transportSecurity, FWID
) on FWID

## 🙋‍♀️ Ask for the community
1. Please vote this issue up (👍) to prioritize it.

**Comment by arthurclares** [comment]
Thank you for that @MS-mikeo. I'm adding this fix to the next month release. 
@sebassem FYI.

**Comment by MS-mikeo** [comment]
[like]  Mike O'Shaughnessy reacted to your message:
________________________________

**Comment by arthurclares** [comment]
@MS-mikeo Mike, I made a very small change to the code as the intent of this query is to find Premium Firewall with Premium Firewall policies that does not use premium features, such as TLS or IDPS.
resources 
| where type =~ 'Microsoft.Network/azureFirewalls' and properties.sku.tier=="Premium"
| project FWID=id, firewallName = name, SkuTier = tostring(properties.sku.tier), resourceGroup, location
| join kind=inner (
    resources
    | where type =~ 'microsoft.network/firewallpolicies'
    | mv-expand properties.firewalls
    | extend intrusionDetection = tostring(properties.intrusionDetection contains "Alert" or properties.intrusionDetection contains "Deny"), transportSecurity = tostring(properties.transportSecurity contains "keyVaultSecretId")
    | extend FWID=tostring(properties_firewalls.id)
    | where intrusionDetection == "False" and transportSecurity == "False"
    | project PolicyName = name, PolicySKU=tostring(properties.sku.tier), intrusionDetection, transportSecurity, FWID
) on FWID

The Advisor workbook should be updated in 2 weeks and the Toolkit workbook should be updated in about ~3 weeks. Let me know if you need access to the JSON before that and I'm happy to share it with you.

**Comment by arthurclares** [comment]
hey @MS-mikeo Mike, we have released the new version of the workbook with this fix. 
Let me know if you have any questions, otherwise I will close this bug 😃

**Comment by MS-mikeo** [comment]
[heart]         Mike O'Shaughnessy reacted to your message:
________________________________
