### ISSUE TITLE
Bug found in ADF ingestion pipeline when you have duplicate filenames

### ISSUE THREAD

**Issue by thecloudman** [microsoft/finops-toolkit#620]
### Discussed in https://github.com/microsoft/finops-toolkit/discussions/619

<div type='discussions-op-text'>

<sup>Originally posted by **thecloudman** February 27, 2024</sup>
Been doing testing around why my billed cost was not matching exports from usage details. I found that when doing onetime exports, if you had duplicate filenames in your exports, for example you split your July onetime export, you would have part_0_000_01.csv in one folder and part_0_000_01.csv in another folder. When you run the ingestion pipeline, the convert to csv will overwrite data in the existing filename. To overcome this i changed the Set FileName variable from: **@replace(pipeline().parameters.fileName, '.csv', '.parquet'**) to **@concat(replace(pipeline().parameters.fileName, '.csv', ''), '_', formatDateTime(utcNow(), 'yyyyMMddHHmmss'), '.parquet')**. This appends a date format to the end of the file and creates a unique filename for each imported file. It prevents overwriting the original parquet file.</div>

**Comment by flanakin** [comment]
This should be resolved in 0.6
