### ISSUE TITLE
Deployment the finops-hub template failed 

### ISSUE THREAD

**Issue by fgYanina** [microsoft/finops-toolkit#634]
Hi, when i try to deploy finops-hub template, i recibe this error:

Deployment template validation failed: 'The template resource '/add' for type 'Microsoft.KeyVault/vaults/accessPolicies' at line '1' and column '3464' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-syntax-resources for usage details.'. (Code: InvalidTemplate)

can you help me?

thanks

**Comment by fgYanina** [comment]
yes, now is ok, thanks

**Comment by arthurclares** [comment]
This is fixed on the newly release version 0.3.

**Comment by psilantropy** [comment]
Hi team. Let me know if you want a new issue for below;

I didn't have this issue with the hub upgrade .21rc to .3 this morning, but I do get InvalidTemplate when deploying the workbooks via your deployment link here: https://microsoft.github.io/finops-toolkit/optimization-workbook

`{"code":"InvalidTemplate","message":"Deployment template parse failed: 'Error reading string. Unexpected token: StartObject. Path '['Microsoft.Insights/workbooks']'.'."}`

Same issue with the governance workbook.

I deployed manually instead.
