### ISSUE TITLE
AHB report in Cost Optimization Workbook does not correctly show servers without AHB

### ISSUE THREAD

**Issue by jmcCapMgmt33** [microsoft/finops-toolkit#638]
## 🐛 Problem
TODO: Add a clear and concise description of what the bug is.

## 👣 Repro steps
TODO: Add repro steps below:
1. Go to
2. Click on
3. Scroll down to

## 🤔 Expected
TODO: AHB report: VMs without AHB, does not correctly report on VMs without AHB.  In the report, VMs with AHB are shown but in other reports in Azure, the same servers are present showing they have AHB enabled.

## 📷 Screenshots
TODO: N/A

## ℹ️ Additional context
TODO: N/A

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by arthurclares** [comment]
@jmcCapMgmt33 Thank you for submitting this feedback. Which AHB tab you are seeing this issue? 
We identified and fixed an error on the SQL VMs tab. This fix should be published in the Azure Portal in about 7 days.

**Comment by arthurclares** [comment]
hi @jmcCapMgmt33 Just a gentle reminder about this bug.

**Comment by arthurclares** [comment]
This has been fixed on APril's release.
