### ISSUE TITLE
Azure cost management Authentication failed while opening CommitmentDiscounts.pbit

### ISSUE THREAD

**Issue by pankaj392** [microsoft/finops-toolkit#640]
Hello Team,

I installed Finopshub 2.1 tool kit and also able to upload the cost summary power BI report without any problem. But while opening CommitmentDiscounts.pbit power BI report, I am getting authentication error for Azure cost management to pull out the recommendation.

I believe I have sufficient rights (enrollment reader role) in cost management portal as I can manually access and open azure portal and navigate to recommendation without any problem . I am using same organization email ID but not sure why this PowerBI report is giving this error (screenshot attached). Any idea how can I see which URL for cost management power BI report is trying to open?

<img width="555" alt="Authentication_error" src="https://github.com/microsoft/finops-toolkit/assets/140919130/630b637f-4d97-424f-bdf5-79b531852801">

Please let me know how can I fix this.Thanks in advance,

Regards,
Pankaj Sharma

**Comment by arthurclares** [comment]
Hello Pankaj,
The commitment savings data require you to specific your EA enrollment number (Or billing profile for MCA). There are some additional steps to setup this report. Can you please review [this guide ](https://microsoft.github.io/finops-toolkit/power-bi/setup#-setup-your-first-report)(Step 2) and let me know if that works for you?

**Comment by pankaj392** [comment]
Thanks or the hint. Issue is resolved based on your suggestion. I corrected the scope ID according to my profile in cm connector setup.
