### ISSUE TITLE
Token error when deploying as custom template

### ISSUE THREAD

**Issue by simonarbel** [microsoft/finops-toolkit#652]
when deploying the template for a customer, getting the following error:

{"code":"DeploymentFailed","target":"/subscriptions/e9c7b2d8-706f-45c5-814c-c99d32418cc1/resourceGroups/FinOps-Toolkit/providers/Microsoft.Resources/deployments/hub","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"ResourceDeploymentFailure","target":"/subscriptions/e9c7b2d8-706f-45c5-814c-c99d32418cc1/resourceGroups/FinOps-Toolkit/providers/Microsoft.Resources/deployments/storage","message":"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'.","details":[{"code":"DeploymentFailed","target":"/subscriptions/e9c7b2d8-706f-45c5-814c-c99d32418cc1/resourceGroups/FinOps-Toolkit/providers/Microsoft.Resources/deployments/storage","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"ResourceDeploymentFailure","target":"/subscriptions/e9c7b2d8-706f-45c5-814c-c99d32418cc1/resourceGroups/FinOps-Toolkit/providers/Microsoft.Resources/deploymentScripts/uploadSettings","message":"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'failed'.","details":[{"code":"DeploymentScriptOperationFailed","message":"The received access token is not valid: at least one of the claims 'puid' or 'altsecid' or 'oid' should be present. If you are accessing as application please make sure service principal is properly created in the tenant."}]}]}]}]}

The customer is the owner of the subscription. 
Also when trying to deploy the template thru the link, we get CORS error.

Any idea how to solve this?

**Comment by flanakin** [comment]
This is the core error: 
> _The received access token is not valid: at least one of the claims 'puid' or 'altsecid' or 'oid' should be present. If you are accessing as application please make sure service principal is properly created in the tenant._

I've never seen that. Given it's about the token, I don't think this is about anything in the toolkit. I would contact support and have them help investigate. Can you look at the resource group deployment and see which resource is failing? That will help identify which team to file the support request against.

**Comment by flanakin** [comment]
FYI - Here's what Copilot tells me:

The error message "**The received access token is not valid: at least one of the claims 'puid' or 'altsecid' or 'oid' should be present. If you are accessing as an application, please make sure the service principal is properly created in the tenant**" typically occurs when working with **Azure resources** through **REST API** or **service principals**. Here's what it means and how to address it:

1. **Service Principal Existence**:
    - The error suggests that the **service principal** for your app does not exist in the **tenant** where you're trying to access resources.
    - Each tenant you want to access must **consent** to your application. This ensures that the service principal exists in their tenant and has the necessary permissions to access Azure APIs.

2. **Consent and Permissions**:
    - Ensure that your application has been **properly registered** as a service principal in the Azure AD tenant.
    - Verify that the service principal has the **required permissions** to access the specific Azure resources you're trying to interact with.

3. **Troubleshooting Steps**:
    - **Check** if the service principal exists in the target tenant.
    - **Review** the permissions assigned to the service principal.
    - **Ensure** that the client ID, secret, and tenant ID are correctly configured in your application.

Remember that resolving this issue involves verifying the service principal's existence, permissions, and proper configuration. Once you've addressed these aspects, you should be able to obtain a valid access token. 🚀

Source: Conversation with Bing, 4/1/2024
(1) Login with service principal fails: The received access token is not .... https://github.com/Azure/login/issues/233.
(2) I'm trying to access Azure resources through rest api i'm getting error .... https://learn.microsoft.com/en-us/answers/questions/422615/im-trying-to-access-azure-resources-through-rest-a.
(3) The received access token is not valid - Microsoft Q&A. https://learn.microsoft.com/en-us/answers/questions/979522/the-received-access-token-is-not-valid.
(4) Access Token seems to be invalid - social.msdn.microsoft.com. https://social.msdn.microsoft.com/Forums/vstudio/en-US/b50969f1-894b-48e9-8645-bbe0bbfd8e49/access-token-seems-to-be-invalid?forum=WindowsAzureAD.
(5) undefined. http://stackoverflow.com/questions/40498446/azure-invalid-accesstoken.
