### ISSUE TITLE
PowerBI - Data Ingestion report

### ISSUE THREAD

**Issue by gowen-x** [microsoft/finops-toolkit#674]
Just looking at upgrading my environment to 0.3 and am interested in the Data Ingestion report. 
However, the currently download has a sensitivity label applied to it so it can't be used. 

Is this internally testing right now? Or an oversight?

**Comment by arthurclares** [comment]
@gowen-x Just to double check, which file you used? the .pbit or .pbix one?

**Comment by flanakin** [comment]
@gowen-x Sorry for the inconvenience! Just uploaded new versions of both the pbit and pbix files just in case.
