### ISSUE TITLE
Add UnitPrice back into the dataset

### ISSUE THREAD

**Issue by thecloudman** [microsoft/finops-toolkit#675]
## ⚠️ Problem
In Cost management data the column UnitPrice is available which allows practitioners to derive savings and other cost data. IN the FOCUS export this column has been removed. 

## 🛠️ Solution
Please provide the UnitPrice column in the FOCUS export.

**Comment by flanakin** [comment]
`UnitPrice` in amortized data maps to `x_OnDemandUnitPrice` in the FOCUS data. Are you noticing any issues with the data?

**Comment by thecloudman** [comment]
> `UnitPrice` in amortized data maps to `x_OnDemandUnitPrice` in the FOCUS data. Are you noticing any issues with the data?

Thanks. No issues with the data that i can see for now.
