### ISSUE TITLE
AHB enabled cores incorrect when using SQL Elastic Pools

### ISSUE THREAD

**Issue by pvansteenkiste** [microsoft/finops-toolkit#685]
## 🐛 Problem
When I check the "SQL DB AHB Consumed Cores per VM" it seems like it adds up all databases on a SQL Elastic Pool ?  For instance: we have 23 databases on a SQL Elastic pool with 6vcores.  Then 23x6 is calculated as SQL DB AHB Consumed Cores ?  (while of course the AHB is enabled on the Elastic Pool level).  This means the overview is unusable to correctly reflect the REAL number of vcores consumed with AHB

## 👣 Repro steps
1. Go to Rate Optimization - Azure Hybrid Benefit - SQL DB

## 🤔 Expected
I expect the value to be correct.

## 📷 Screenshots
![image](https://github.com/microsoft/finops-toolkit/assets/35564924/6c6b5b36-93cc-45e1-9815-7b9f2887c122)

![image](https://github.com/microsoft/finops-toolkit/assets/35564924/44984a2e-2190-40f1-85c4-9c51ada364bc)

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by arthurclares** [comment]
Hello @pvansteenkiste 
Acknowledged.  Thank you for submitting this. 
I will work on this and revert back with the fix.

**Comment by arthurclares** [comment]
Hello @pvansteenkiste 
There was an error on the queries used to generate these pie charts. I've changed it and it will be published to Advisor at the end of this month.

**Comment by arthurclares** [comment]
Let me know if you can't wait until the end of the month to have this fixed and I can make it available on the Toolkit (Which has a faster publishing process).

**Comment by pvansteenkiste** [comment]
Hi Arthur,

No no, I can wait until the end of the month 😊. Thank you for your effort !!

Best regards

Philippe


Van: Arthur Clares ***@***.***>
Datum: woensdag, 17 april 2024 om 16:56
Aan: microsoft/finops-toolkit ***@***.***>
CC: Philippe Vansteenkiste ***@***.***>, Mention ***@***.***>
Onderwerp: Re: [microsoft/finops-toolkit] AHB enabled cores incorrect when using SQL Elastic Pools (Issue #685)

Let me know if you can't wait until the end of the month to have this fixed and I can make it available on the Toolkit (Which has a faster publishing process).

**Comment by pvansteenkiste** [comment]
Hello Arthur,
Any idea on when it will be fixed in Azure Advisor ?

best regards,

Philippe

**Comment by pvansteenkiste** [comment]
HI Arthur,

When should it be fixed in Azure Advisor ?

Best Regards,

Philippe

**Comment by arthurclares** [comment]
@pvansteenkiste The portal should be updated. Can you confirm if you see the SQL Elastic Pool tab under SQL Databases?
![image](https://github.com/microsoft/finops-toolkit/assets/53261392/c1431d19-148f-4166-a393-506fc9696ba6)

**Comment by arthurclares** [comment]
Closing this as this query has been added to May's update.
