### ISSUE TITLE
Cost Summary PowerBI report - x_ResourceParentName errors 

### ISSUE THREAD

**Issue by MS-mikeo** [microsoft/finops-toolkit#691]
## 🐛 Problem
I helped a customer deploy FinOps hubs 0.2.1-rc3 and they are having an issue where x_ResourceParentName is coming in as null for 52 rows.  This account was transitioned to an MCA account from EA on 4/2 & we are only using the new MCA account data exported as FOCUS. 

## 👣 Repro steps
TODO: Add repro steps below:
Anytime the refresh is ran, this error will continue.

## 🤔 Expected
No errors on the data refresh.

## 📷 Screenshots
![image](https://github.com/microsoft/finops-toolkit/assets/130005316/0f9e477d-6974-46f8-8e19-05eb004a8a96)

![image](https://github.com/microsoft/finops-toolkit/assets/130005316/e29e5bd6-789c-4ba6-923e-9124e73db0a0)

![image](https://github.com/microsoft/finops-toolkit/assets/130005316/45e7729a-b24b-445c-935d-b7f9798724cd)

**Comment by flanakin** [comment]
@MS-mikeo Sorry for missing this one. Do you know what was in the `Tags` column for these rows? Null is expected for most rows. I'm guessing Tags may have been null 🤔

**Comment by MS-mikeo** [comment]
@flanakin - This was from an engagement back in April.  At the time I was looking for this list as I did not know it existed.  https://microsoft.github.io/finops-toolkit/resources/data-dictionary. That will be helpful when I am looking through issues like this.  We can probably close this one out for now.  I will have to follow up with the customer to see what was in the tags column for those.  I know other customers have non tagged resources, so I am not sure how that would result in the errors. 

I do have a question though on tags in the report. I have been assisting others in breaking out their tags to other columns in order to create filters in their reports based on their tagging.  One of the steps I do as part of this is changing the null values in tags to {} before I convert to JSON and parse them out.  Would this cause any issues down the line?

**Comment by flanakin** [comment]
> At the time I was looking for this list as I did not know it existed. https://microsoft.github.io/finops-toolkit/resources/data-dictionary.

I added this to an issue tracking some troubleshooting improvements. Let me know if there are any specific places that adding this would have helped.

> I have been assisting others in breaking out their tags to other columns in order to create filters in their reports based on their tagging.

I'd love to know what you're doing here. We've talked about doing something like this as well. If you have something, it might be a good opportunity to contribute 🙂

> One of the steps I do as part of this is changing the null values in tags to {} before I convert to JSON and parse them out. Would this cause any issues down the line?

No, this shouldn't be an issue. I debated doing this by default. If it's helpful, we can do that in the next release to save you at least one step.
