### ISSUE TITLE
Advisor | Workbooks | Cost Optimization (Preview) - Missing Exports for some tables

### ISSUE THREAD

**Issue by ElanShudnow** [microsoft/finops-toolkit#692]
Hi, using the following workbook: Advisor | Workbooks | Cost Optimization (Preview)

Some of the tables are missing export options such as:
Managed Disk - Snapshots with deleted source disk
Idle Backups
And more

Can we please add export options for each table that exists within this workbook?

**Comment by arthurclares** [comment]
@ElanShudnow Thank you for the feedback, I'm adding it to the backlog and will get this addressed before our next release in May.
