### ISSUE TITLE
[Hubs] Register the EventGrid RP as part of the template

### ISSUE THREAD

**Issue by flanakin** [microsoft/finops-toolkit#696]
## 🐛 Problem
Data is not ingested if someone forgets to register the EventGrid RP.

## 👣 Repro steps
1. On a new subscription, confirm the EventGrid RP is not registered.
2. Deploy the FinOps hubs template.
3. Go to the ADF resource > Launch Studio > Manage > Triggers.
4. Verify the msexports_FileAdded trigger is Started (it should be stopped)
5. Start the trigger, the select the **Publish all** button to commit that change (this should fail)
6. Open the notifications pane and select **View details** to see why it failed

The error should explain that the EventGrid RP hasn't been registered.

## 🤔 Expected
Automate the EventGrid RP registration as part of template deployment.

## ℹ️ Additional context
While ARM does a good job of registering RPs for resources that are included in a template, ADF creates the EventGrid resource behind the scenes when the trigger is started. ADF doesn't register the RP, so it needs to be done explicitly.

We need to investigate if there is a way to declare some RP is needed as part of the template so ARM will auto-register. If not, we can create a script that registers the desired RPs. We can leverage the Initialize-FinOpsHubDeployment command if deployment scripts support installing modules from the PowerShell gallery. Alternatively, we just do the direct RP registration ourselves. The nice part about using our command is that it will cover any new pre-deployment steps that come up over time. 

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by didayal-msft** [comment]
Will go the PowerShell route.

https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-providers-and-types#register-resource-provider mentions that the provider must be registered manually if one resource type creates another.

"Sometimes, a resource in the template requires supporting resources that aren't in the template. Common examples are monitoring or security resources. You need to register those resource providers manually."
