### ISSUE TITLE
AHB (Azure Hybrid Benefit) Cores incorrect for VMSS in the Cost Optimization Workbook

### ISSUE THREAD

**Issue by kasimrehman** [microsoft/finops-toolkit#698]
## 🐛 Problem

1. It seems that each entire VMSS is counted as the cores of only one instance VM  regardless of the number of instances. One would expect a sum of all cores across all instances of the VMSS with each instance being at least 8 cores. Windows licenses are charged per instance so it would make sense to apply the AHB per instance, too.

2. It seems "Cores not enabled per AHB Priority" is always the same as "Consumed Cores per AHB Priority" in the pie chart. The table below seems to show correct (except what is described in 1.) data but the corresponding pie chart is showing something different. The query for the pie chart, in Line 3427 seems to refer to a query called "VMSSAHBEnabled-RG" even though this should be the case for VMSS AHB Disabled. Line 3714 shows that the query for the table correctly uses "VMSSAHBDisabled-RG" instead.

## 👣 Repro steps

1. Create a VMSS with AHB enabled with multiple instances each having, say, less than 8 cores. 
2. "Consumed Cores per AHB Priority" only increase by 8.
3. "Cores not enabled per AHB Priority" also increase by 8 even though no VMSS without AHB enabled was created.
## 🤔 Expected

"Consumed Cores per AHB Priority" should increase by n*max(8,vCores) where n is the number of instances and vCores is the number of cores in each instance. "Cores not enabled per AHB Priority" should not change in this case at all.

**Comment by arthurclares** [comment]
@kasimrehman Thank you for the feedback, I will get this fixed in our next release (Later this month).

**Comment by arthurclares** [comment]
Adding this July's release.
