### ISSUE TITLE
Commitment Discounts PowerBI report - problem with Cost Management connector MCA

### ISSUE THREAD

**Issue by MS-mikeo** [microsoft/finops-toolkit#702]
## 🐛 Problem
When connecting an MCA customer to the Cost Management connector piece of the Commitment Discounts PowerBI report, there are errors for the RecommendationsSingle table (normalizedSize column) and RecommendationsShared table (recommendedQuantityNormalized column) saying that the columns are not found.

## 👣 Repro steps
Connect an MCA customer to the Cost Management connector piece of the Commitment Discounts PowerBI report.

## 🤔 Expected
Populate the tables so that recommendations tabs work in the PowerBI report.

## 📷 Screenshots
**Initial issue (data was populating those columns):**
![image](https://github.com/microsoft/finops-toolkit/assets/130005316/b7c516bc-a0d0-48a2-ab14-37bc956b5ac7)

![image](https://github.com/microsoft/finops-toolkit/assets/130005316/d6652d59-52af-4d40-8c65-1624ca7947d5)

![image](https://github.com/microsoft/finops-toolkit/assets/130005316/8c7c175c-4298-49ad-893b-f0f47eac4857)

**After trying to update queries from steps mentioned in similar issue (https://github.com/microsoft/finops-toolkit/issues/493#issuecomment-1926416386):** 

![image](https://github.com/microsoft/finops-toolkit/assets/130005316/0f995e80-e6a0-412b-a207-56e65c2b797b)

![image](https://github.com/microsoft/finops-toolkit/assets/130005316/95c416df-89a9-4898-a63f-fff7e077eb7d)

**Comment by arthurclares** [comment]
@flanakin Wondering if this issue is related to this comment: https://github.com/microsoft/finops-toolkit/issues/604#issuecomment-1973168293 #604

**Comment by flanakin** [comment]
@arthurclares Agreed. That's what it sounds like.

@MS-mikeo What version of the Power BI report is this? (You can find the version on the first tab.) We fixed this once, so it should be resolved in the latest version. Do you still see this if you download the [latest](https://aka.ms/ftk/latest) reports?

**Comment by MS-mikeo** [comment]
@flanakin - Here is the feedback from the customer as of Friday 5/24.

"I downloaded the committed discounts powerbi report again. the recommendations are still empty.
I used the billing account and billing profile for the scope.
 
I also noticed that for reservation I don't get a list or on-demand cost which is needed to calculate the actual savings. It doesn't matter whether I look at the commitments, savings, prices, or chargeback tab. I don't have a way to calculate the actual savings for the RI, only the savings plan. This is what I wanted to see to be able to show managment how much we are saving with the RIs vs the savings plan."

**Comment by saleemmy** [comment]
I am also getting the same errors, unable to connect to either MCA or CM

**Comment by flanakin** [comment]
I'll add this to the next release so we can try to get it resolved. It should be quick.

**Comment by CaddyG** [comment]
Just to document that we saw this today as well for an MCA.
![image](https://github.com/microsoft/finops-toolkit/assets/126517812/afb0b15b-03c5-4cb8-858d-b99e7c8e7923)

**Comment by flanakin** [comment]
Turns out this was fixed in the Cost Management connector report, but not the Commitment discounts report. I just submitted PR #766 to fix this. Feel free to check out the changes and add any comments, if you're familiar with Power Query M language 🙂 We always love extra reviewers! We'll probably close this quickly, but if anyone has any comments, we can address them separately.
