### ISSUE TITLE
Commitment Discounts - This file is restricted

### ISSUE THREAD

**Issue by usvjosh** [microsoft/finops-toolkit#704]
## 🐛 Problem
The CommitmentDiscounts.pbit file is giving me an error message about the file being restricted. I get this error on a company computer as well as a non-company computer. The other pbit files work just fine. I'm not sure how to work around this issue. 

https://github.com/microsoft/finops-toolkit/releases/download/v0.3/CommitmentDiscounts.pbit

## 👣 Repro steps
1. Download the file
2. Open it in power bi desktop (or just open the file)
3. error shows up

## 🤔 Expected
Normally it lets you configure the data sources and you can use the report. 

## 📷 Screenshots
![image](https://github.com/microsoft/finops-toolkit/assets/72226463/f86a0924-16f4-4812-88cd-50f96dec3377)

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
4. Leave comments to help us solidify the vision.

**Comment by arthurclares** [comment]
@usvjosh We have uploaded a new copy of the file, can you see if that works? https://github.com/microsoft/finops-toolkit/releases/download/v0.3/CommitmentDiscounts.pbit
Also, just making sure do you want to use the .PBIT (Template) and not .PBIX file? PBIX works for most of the scenarios.

**Comment by usvjosh** [comment]
That file opens correctly now but I'm not seeing all the data source connection options. We do want the template file because it works with the finops hub, the datalake/storage account side directly. I use the storage account key to have it load data. This lets us do scheduled refresh in power bi. If i use the windows account sign in, it won't work in power bi for scheduled refresh. The other template files work just fine, just this one is wonky. Thank you for the help so far. 

![image](https://github.com/microsoft/finops-toolkit/assets/72226463/c4c4f828-07dc-422e-b542-4a763b1a9678)

![image](https://github.com/microsoft/finops-toolkit/assets/72226463/c04c9daf-1756-48d3-961f-9deb7a9bb07e)


![image](https://github.com/microsoft/finops-toolkit/assets/72226463/4087b9ee-77d7-45c7-bd39-6496aa980525)

**Comment by flanakin** [comment]
@usvjosh The second screenshot is for the Cost Management connector, which only supports a user account or service principal. This one isn't the storage account, so you won't be able to use a storage account token.

**Comment by flanakin** [comment]
@usvjosh Just to add to this, the Cost Management connector is optional here. It's used to pull reservation recommendations. If you're okay with not having that, you do not need to specify those connection details. I recall testing that at one point, so it should still work without signing in unless there was a regression. Let us know what you find.

**Comment by usvjosh** [comment]
@flanakin That all makes sense to me now. It's a bit of a pain to have to manually refresh the data in the report, then republish it to power bi. We watch our azure reservations and savings plans very closely. I was hoping for something more automatic. I know a lot of the data needed to show azure costs savings is in the cost export (finops hub components). I have a custom report to show the savings. We also wanted a standardized report from MSFT that could do the same for comparison. Thank you for the help with this too.
