### ISSUE TITLE
FinOps Hub version

### ISSUE THREAD

**Issue by saleemmy** [microsoft/finops-toolkit#717]
My finops hub version shows 0.3, but on the website it says updated version is 0.2 and it is mentioned to upgrade. Can you someone clarify pls if there is separate doc and instructions for 0.3.

the new powerbi reports that I dowloaded are not working.

**Comment by flanakin** [comment]
0.3 is the latest. Where do you see 0.2?

**Comment by arthurclares** [comment]
@saleemmy Are you still facing issues?

**Comment by saleemmy** [comment]
Yes, some of the views are showing blank. The commitments report shows lower savings in May compared to previous months, though I purchased more savings plan and RIs. Not sure what changed in the calculations. Also the RI and SP costs show as blank under subscriptions or resource groups. The RI and SP would be distributed across the applied resources.

**Comment by arthurclares** [comment]
@saleemmy Thank you for the update and providing more details on the issues you're experiencing.

From your initial report, it seems like there are two main concerns:

1. FinOps Hub Version Discrepancy:
Question: Are is the version that you are using? 0.2 or 03? You can check that by going to the Storage Account, then open the config container and check the settings.json file. 
2. PowerBI Report Issues:
There are no changes in the calculation between one month to another. Which tab are showing blank results?

 Do you have any Microsoft person (Cloud Solution Architect, for example) already working with you?

**Comment by flanakin** [comment]
@saleemmy, I'm going to close this since we haven't heard back in over a month. If you get a chance to share details, we can open it again. Just want to clean up the list a bit.
