### ISSUE TITLE
Not able to refresh the PowerBI report after publishing

### ISSUE THREAD

**Issue by josesarsa** [microsoft/finops-toolkit#721]
I have published the PowerBI template for commitment discount but when I try to stablish an automatic refresh, I received an error about an storage account that is not under my control(It is the default one). I can not remove it to make the refresh work

![image](https://github.com/microsoft/finops-toolkit/assets/89536192/8469c778-dc1e-4453-8a97-04aac749f6df)

**Comment by josesarsa** [comment]
![image](https://github.com/microsoft/finops-toolkit/assets/89536192/b16fb63e-4aaa-46c3-ab6c-ce6c91bb7945)

**Comment by flanakin** [comment]
The ccmstorageprod storage account should work with anonymous access. Can you try that and let us know if you're still facing an issue? We'll keep this open to track at least documenting that so it's not a mystery.

**Comment by josesarsa** [comment]
There was a default enrollment id, I fixed thanks
