### ISSUE TITLE
Export of all cost optimization workbook recommendations into one report

### ISSUE THREAD

**Issue by mayaazar** [microsoft/finops-toolkit#725]
I have recently delivered the Azure cost optimization assessment VBD to a strategic customer in the UK. They have asked if it is possible to export all the recommendations from the cost optimization workbook automatically and for specific tags into a single report so they can create jira tickets in this way. Could you please advise if this is something possible or on the roadmap?

**Comment by sebassem** [comment]
Unfortunately this is not possible from a workbook perspective as the export capability is per query.
