### ISSUE TITLE
ListCost calculation not correct

### ISSUE THREAD

**Issue by DirkBrinkmann** [microsoft/finops-toolkit#727]
## 🐛 Problem
TODO: Based on a customer FOCUS export from end of May with Data from April I noticed that ListCost <> List Unit Price x Pricing Quantity
It seems, that the dimension of the Pricing Quantity is not always correct.

## 👣 Repro steps
None

## 🤔 Expected
TODO: According to the FOCUS Specification, ListCost = List Unit Price x Pricing Quantity

## 📷 Screenshots
TODO: If applicable, add screenshots to help explain your problem. Remove if not applicable.
![image](https://github.com/microsoft/finops-toolkit/assets/19854016/5b054b9d-8acd-4af4-b353-3e96bfc7a59d)

## ℹ️ Additional context
N/A
## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by flanakin** [comment]
Discussed this with Dirk offline. This is a Cost Management issue that will be raised with support. We'll keep this open to track it.

**Comment by flanakin** [comment]
@DirkBrinkmann Any updates on this from support?

**Comment by DirkBrinkmann** [comment]
> @DirkBrinkmann Any updates on this from support?

@flanakin Unfortunately not.

**Comment by flanakin** [comment]
Turns out the PricingQuantity column in FOCUS datasets was not using the correct value when x_PricingBlockSize was > 1. This issue has been resolved. We recommend re-exporting data for the full year to address this. It will impact anything using PricingQuantity or ContractedCost columns.
