### ISSUE TITLE
Narration is needed for several services In optimization workbook.

### ISSUE THREAD

**Issue by rithinkumark1** [microsoft/finops-toolkit#732]
## ⚠️ Problem
TODO: Narration is needed for several services in the optimization workbook to provide more context. For example, for the web apps in the app service tab, some instances are listed, but it doesn’t mention recommended actions for these instances. The same is true for the following sections of the notebook:
-	Log Analytics workspaces
-	App Services

Provide a download option for the list of Idle backup.

## 🛠️ Solution
TODO: Please provide accurate action plans for each services on what exactly is the optimization recommendations.

## ℹ️ Additional context
TODO: Webapps Narration missing. What is the action plan recommended for these Webapps?
![image](https://github.com/microsoft/finops-toolkit/assets/169157529/62bf8f7e-6461-4e8c-b308-d6ef9b280436)

What is the action plan recommended for these log analytics workspace? Don't see nay specific recommendations for these workspaces.
![image](https://github.com/microsoft/finops-toolkit/assets/169157529/f4b94671-8483-4ef8-b1a1-2fc0225a80e5)

Don't see a download option to export the list of idle backup. 
![image](https://github.com/microsoft/finops-toolkit/assets/169157529/43cc364d-2725-4535-8bfd-0709de36bfdc)

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by rithinkumark1** [comment]
For AKS as well. I can see a list of AKS instances, but there is no recommended action narrated for these instances.
![image](https://github.com/microsoft/finops-toolkit/assets/169157529/7549031d-122b-4697-94f0-c3dc0aa5b742)

**Comment by sebassem** [comment]
@rithinkumark1 Thanks for opening this issue, the narrative for each query is the red textbox above it, the recommendations here are subjective depending on each customer's scenario, so we provide the best practices and some considerations in the textbox then the query shows the information that you need to take a decision (if its applicable to your scenario)

**Comment by rithinkumark1** [comment]
@sebassem Understood. But the best practices are already available in the Microsoft documentation. the resource listed in the table should provide some input on the actions required, otherwise it fails the purpose of having a list of resources in the workbook without knowing what to do with it.

![image](https://github.com/microsoft/finops-toolkit/assets/169157529/22f1bc36-377c-464a-a08d-b6b54750cd19)

**Comment by sebassem** [comment]
@rithinkumark1 Got your point, in the next release we can try to make it clearer. In the screenshot you shared for AKS, you see four best practices, you will see in the resource list columns fields that show the current state of your clusters against those recommendations. Its up to you to decide if it makes sense to apply this recommendation or not. For example: Does it make sense to use spot VMs for this cluster or not?

**Comment by rithinkumark1** [comment]
@sebassem Thanks. In My i look forward to the iteration. Honestly it would make more sense to put the exact recommendation for the list of resources (for eg like Idle resources/orphaned) than the best practices. If we consider just best practices then again, we need to spend time and efforts to research on it.
