### ISSUE TITLE
Detected Type Mismatches with latest Hub and Power BI file.

### ISSUE THREAD

**Issue by lundejd** [microsoft/finops-toolkit#736]
I decided to start fresh and deploy the latest version of FinOps hub and download the latest CostSummary Power BI file (v24.03.18). Followed the same process I did earlier this year but now I'm getting thousands of errors when I pull cost data. (no customizations at all)

(Note: I get the same errors when run against my older hub deployment that fully works with the older version of the cost summary report. This tells me v24.03.18 is the source of the error.)

When I look at the Query Errors the Appled Steps shows Source, Detected Type Mismatches, Added Index, Kept Errors, Reordered Columns. Power BI not being very intelligent about saying where the errors are happening.

This is the Detected Type Mismatches error:

= let
    tableWithOnlyPrimitiveTypes = Table.SelectColumns(Source, Table.ColumnsOfType(Source, {type nullable number, type nullable text, type nullable logical, type nullable date, type nullable datetime, type nullable datetimezone, type nullable time, type nullable duration})),
    recordTypeFields = Type.RecordFields(Type.TableRow(Value.Type(tableWithOnlyPrimitiveTypes))),
    fieldNames = Record.FieldNames(recordTypeFields),
    fieldTypes = List.Transform(Record.ToList(recordTypeFields), each [Type]),
    pairs = List.Transform(List.Positions(fieldNames), (i) => {fieldNames{i}, (v) => if v = null or Value.Is(v, fieldTypes{i}) then v else error [Message = "The type of the value does not match the type of the column.", Detail = v], fieldTypes{i}})
in
    Table.TransformColumns(Source, pairs)

I narrowed the errors to this line. I commented it out and placed the older version back in and now its error free:

    // AHB columns
    //SkuDetails_expand   = Table.ExpandRecordColumn(ExpandedTags, "tmp_SkuDetails",
    SkuDetails_expand   = Table.ExpandRecordColumn(ParsedArrays, "x_SkuDetailsDictionary",

**Comment by arthurclares** [comment]
@lundejd Can you double check if you your cost export is set to use FOCUS and not amortized cost? I've seen something similar in the past and that was the issue.

**Comment by lundejd** [comment]
It is for sure type “Cost and usage details (FOCUS)” including all back fill month, all dataset 1.0-preview(v1)

From: Arthur Clares ***@***.***>
Date: Tuesday, June 11, 2024 at 8:21 AM
To: microsoft/finops-toolkit ***@***.***>
Cc: John Lundell ***@***.***>, Mention ***@***.***>
Subject: Re: [microsoft/finops-toolkit] Detected Type Mismatches with latest Hub and Power BI file. (Issue #736)

@lundejd<https://github.com/lundejd> Can you double check if you your cost export is set to use FOCUS and not amortized cost? I've seen something similar in the past and that was the issue.

**Comment by flanakin** [comment]
I'll take a look. I haven't noticed any issues, which leads me to guess that some service is generating malformed JSON in the x_SkuDetails (AdditionalInfo) column. Can you share what you have in x_SkuDetails for one of the rows that's failing?

Also, what version of hubs did you previously have setup?

**Comment by lundejd** [comment]
Sure here are a couple. The interesting thing is they all seem to relate to the windows virtual desktop service (WVD) – I’m loading my errors and have yet to see a line that does not contain WVD in one way or another.

{"PipelineType":"v2","DataTransferDirection":"DataTrOut","VmName":"WAWVDS0080-0","ContainerId":"086abbca-7e19-4df1-b282-f247fa044669","NodeId":"d7fdfe6d-4380-cae9-f117-22b388c13d0b","EmittingService":"WVD"}

{"UsageType":"ComputeHR","ImageType":"Windows Client BYOL","ServiceType":"Standard_D8ds_v5","VMName":null,"VMProperties":null,"VCPUs":8,"ConsumedQuantity":1.0,"EmittingService":"WVD","ReservationOrderId":"b4558c2e-d91f-4f80-aeec-b2d65c1de7f2","ReservationId":"8ab28c6c-cc7d-4f90-9c6b-3e463996b926","ConsumptionMeter":"36de03b6-9cd1-558c-b0e0-6992364ef13f","RINormalizationRatio":4.0}

A few of them just say “null”



From: Michael Flanakin ***@***.***>
Date: Tuesday, June 11, 2024 at 9:30 PM
To: microsoft/finops-toolkit ***@***.***>
Cc: John Lundell ***@***.***>, Mention ***@***.***>
Subject: Re: [microsoft/finops-toolkit] Detected Type Mismatches with latest Hub and Power BI file. (Issue #736)

I'll take a look. I haven't noticed any issues, which leads me to guess that some service is generating malformed JSON in the x_SkuDetails (AdditionalInfo) column. Can you share what you have in x_SkuDetails for one of the rows that's failing?

Also, what version of hubs did you previously have setup?

**Comment by arthurclares** [comment]
@lundejd We were able to reproduce and fix the issue on 0.3 - Can you confirm it this file works for you?
https://github.com/microsoft/finops-toolkit/releases/download/v0.3/CostSummary.pbix
I assumed you were looking for .pbix, but let me know if you need .pbit . 
Thank you!

**Comment by lundejd** [comment]
Yes, I was able to test this and its loading without errors now. Thanks!

From: Arthur Clares ***@***.***>
Date: Monday, June 17, 2024 at 2:07 PM
To: microsoft/finops-toolkit ***@***.***>
Cc: John Lundell ***@***.***>, Mention ***@***.***>
Subject: Re: [microsoft/finops-toolkit] Detected Type Mismatches with latest Hub and Power BI file. (Issue #736)

@lundejd<https://github.com/lundejd> We were able to reproduce and fix the issue on 0.3 - Can you confirm it this file works for you?
https://github.com/microsoft/finops-toolkit/releases/download/v0.3/CostSummary.pbix
I assumed you were looking for .pbix, but let me know if you need .pbit .
Thank you!

**Comment by arthurclares** [comment]
Great, thank you for confirming @lundejd !
I will close this issue then 👍🏾
