### ISSUE TITLE
Set MCA billing account ID as scope 

### ISSUE THREAD

**Issue by ptsouk** [microsoft/finops-toolkit#745]
## ⚠️ Problem
MCA Billing account ID has unsupported characters for the "Directory" field when setting the scope of the FOCUS export.

## 🛠️ Solution
Update documentation with the correct setting of the "Directory" field in the case of MCA and billing account scope.

## ℹ️ Additional context
When setting the FOCUS export rule, the "Directory" field requires the resource ID of the scope. In the case of MCA and a scope at the billing account, the MCA billing account ID has the format: 
```
guid:guid_yyyy-mm-dd
```
where the characters ":" and "_" are unsupported.

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by flanakin** [comment]
> where the characters ":" and "_" are unsupported.
😣

Let me follow up with the Cost Management team. Allowed characters shouldn't be blocked.

**Comment by arthurclares** [comment]
@flanakin Meanwhile, should we update the docs to say that we should only use the first part of the string? (everything before ":"  )
