### ISSUE TITLE
Issue with Missing Subscriptions in Power BI Template After Implementing FinOps Hub

### ISSUE THREAD

**Issue by arthursilvany** [microsoft/finops-toolkit#772]
## 🐛 Problem

I implemented the FinOps hub for two different customers, and I've noticed that the Power BI template does not display all the subscriptions when viewing the data. This is the second implementation where I've encountered this issue.

The export configuration is set to "Cost and Usage Focus," and the dataset version is 1.0 preview (v1).

While the CSV file shows all the subscriptions, the issue arises during data processing by the data factory.

**Comment by felipeafeltes** [comment]
My customer is having the same issue. They are using the billing account (/providers/Microsoft.Billing/billingAccounts/###) on the export configuration.

**Comment by CaddyG** [comment]
I have helped another Architect with the same issue and my customer this week experienced the same. Out of 240 subscriptions, we only see two.

**Comment by flanakin** [comment]
We identified the issue. There was an extra filter on the CostDetails query for the CostSummary.pbix file only. You can resolve it by removing the last 2 steps in the query or by downloading the [latest file](https://github.com/microsoft/finops-toolkit/releases/download/v0.3/CostSummary.pbix). Sorry for the inconvenience! We're discussing next steps to avoid this in the future.
