### ISSUE TITLE
Incomplete data in FinOps Hub PowerBI Reports

### ISSUE THREAD

**Issue by Ifyagolu** [microsoft/finops-toolkit#773]
Hello Team, I was able to setup FinOps Hub for my Customer and connected the reports to the Export data but Cost Summary report does not show all the required data in the pages, it shows only one subscription, one region, one Azure service, no commitment details, no raw data etc. Cost Mgt Export is using the EA billing scope and export run succeeded. Commitment Discount report have similar issues. Could you help with this issue?

**Comment by flanakin** [comment]
@Ifyagolu Thanks for reporting this issue. There was an extra filter on the CostDetails query for the CostSummary.pbix file. You can resolve it by removing the last 2 steps in the query or by downloading the [latest file](https://github.com/microsoft/finops-toolkit/releases/download/v0.3/CostSummary.pbix). Sorry for the inconvenience! We're discussing next steps to avoid this in the future.
