### ISSUE TITLE
Cost Optimization workbook lists unattached disks for disk used by pods

### ISSUE THREAD

**Issue by alsanch** [microsoft/finops-toolkit#780]
## 🐛 Problem
Cost Optimization workbook lists unattached disks for disk used by pods (https://learn.microsoft.com/en-us/azure/aks/azure-csi-disk-storage-provision), which adds false positives on this workbook section.  Several customers were already affected by this issue.

## 👣 Repro steps
First, have managed disks used by AKS pods.
Then, go to Azure Advisor, Workbooks, Cost Optimization (Preview), Workload Optimization, Storage, Managed Disks, Unattached disks table.

## 🤔 Expected
These managed disks should not be listed as unattached, since they are used by AKS pods

**Comment by sebassem** [comment]
@alsanch Thanks for flagging this issue, a fix will be included in the next release.
