### ISSUE TITLE
Invalid scopes results in error "ConvertFrom Json

### ISSUE THREAD

**Issue by CaddyG** [microsoft/finops-toolkit#786]
## 🐛 Problem
TODO: Add a clear and concise description of what the bug is.

## 👣 Repro steps
TODO: Add repro steps below:
1. Go to
2. Click on
3. Scroll down to

## 🤔 Expected
TODO: Add a clear and concise description of what you expected to happen.

## 📷 Screenshots
TODO: If applicable, add screenshots to help explain your problem. Remove if not applicable.

## ℹ️ Additional context
TODO: Add any other context about the problem here. Remove if not applicable.

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by helderpinto** [comment]
@CaddyG, can you provide more details? The issue description does not provide any helpful context besides the title. Which operation were you trying when this error was raised? Was this from a PowerShell cmdlet? Which parameters did you use? What is the PowerShell version (call `$PSVersionTable` from the PowerShell prompt to confirm)?

**Comment by flanakin** [comment]
Closing due to missing details
