### ISSUE TITLE
Bug report: Data Factory ingestion (ETL) pipeline doesn't work with FOCUS 1.0

### ISSUE THREAD

**Issue by peter-mogaka** [microsoft/finops-toolkit#802]
## 🐛 Problem
After successfully deploying finops-hub from FinOps toolkit deployment options(https://microsoft.github.io/finops-toolkit/resources/deploy) and configuring ACM cost exports, the Data Factory ingestion ETL pipeline is not triggered, when using FOCUS 1.0 dataset version. 

However, it works fine when using FOCUS **1.0-preview(v1)** 
## 👣 Repro steps**
TODO: Add repro steps below:
1. Deploy finops hub from https://microsoft.github.io/finops-toolkit/resources/deploy
2. Configure Exports with FOCUS 1.0 dataset
3. Check data factory pipeline

## 🤔 Expected
TODO:
1. Add support for FOCUS 1.0 dataset
2. Add documentation/guidance to inform of error with 1.0 dataset

## 📷 Screenshots
![Skjermbilde 2024-07-08 153150](https://github.com/microsoft/finops-toolkit/assets/78694283/ede3ca4f-afa0-4ee9-ab96-d9b28d632723)
![Skjermbilde 2024-07-08 153157](https://github.com/microsoft/finops-toolkit/assets/78694283/d53bf971-9cf7-4ab1-a09d-55d103184be6)

## ℹ️ Additional context
TODO: This issue is discussed in #174 

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
3. Leave comments to help us solidify the vision.

**Comment by flanakin** [comment]
This isn't a bug, but rather a new feature request. The good news is we're working on it 🙂 There are a few PRs out to update docs, PowerShell, and Power BI. I'm working on updating the hubs data ingestion pipeline as we speak. This will be available in the next release very soon.

**Comment by peter-mogaka** [comment]
@flanakin What's the status update on this? I upgraded finops hub to 0.4 yesterday, and the ingestion ETL still fails with FOCUS 1.0 dataset.
It works with 1.0-Preview still.
