### ISSUE TITLE
Azure Optimization Engine Savings Plan Usage workbook: "query failed" error in Savings Plan

### ISSUE THREAD

**Issue by MohnJadden** [microsoft/finops-toolkit#841]
## 🐛 Problem
After deploying Azure Optimization Engine via the steps described at https://microsoft.github.io/finops-toolkit/optimization-engine#-deployment-instructions and waiting a few days, the Savings Plan Usage workbook shows "query failed" in the Savings Plan section.  This results in no data being shown in the workbook.

## 👣 Repro steps
1. Configure resources to send all diagnostic logs to a Log Analytics workspace
2. Deploy Azure Optimization engine to the same Log Analytics workspace
3. Wait 24 hours
4. Go to the same LA workspace -> Workbooks -> click on Savings Plan Usage
5. Receive error

## 🤔 Expected
The Savings Plan Usage report is displayed

## 📷 Screenshots
![image](https://github.com/user-attachments/assets/e25d310a-ba7a-45d3-a84b-e4389a8498b3)

## ℹ️ Additional context
This is a standard pay-as-you-go MCA tenant and subscription.

## 🙋‍♀️ Ask for the community
We could use your help:
1. Please vote this issue up (👍) to prioritize it.
6. Leave comments to help us solidify the vision.

**Comment by helderpinto** [comment]
Thank you for reporting this, @MohnJadden. This workbook depends on the `AzureOptimizationSavingsPlansUsageV1_CL` Log Analytics table to be populated by the `Export-SavingsPlansUsageToBlobStorage` runbook.

If your subscription/MCA does not have any active Savings Plan (SP), then the SP exports are going to return 0 entries and no rows will be ingested in that LA table - the error you're getting is thus expected.

If you trust you have active SPs, then please check whether the aforementioned runbook is generating any exception. It might be a case of lack of permissions by the AOE managed identity at the MCA level. Please, ensure you have followed the steps described [here](https://aka.ms/AzureOptimizationEngine/commitmentssetup) to assign the required permissions to AOE.

**Comment by helderpinto** [comment]
Hi, @MohnJadden. Can you please confirm whether you were able to solve the issue?
