### ISSUE TITLE
Azure Optimization Engine Reservations Potential workbook error in Estimated Commitment and Savings: 'where' operator: Failed to resolve table or column expression named 'AzureOptimizationPricesheetV1_CL

### ISSUE THREAD

**Issue by MohnJadden** [microsoft/finops-toolkit#842]
## 🐛 Problem
After deploying Azure Optimization Engine via the steps described at https://microsoft.github.io/finops-toolkit/optimization-engine#-deployment-instructions and waiting a few days, the Reservations Potential workbook shows an error in the Estimated Commitment and Savings section: `'where' operator: Failed to resolve table or column expression named 'AzureOptimizationPricesheetV1_CL'...`  Clicking Refresh does not cause any changes.

## 👣 Repro steps
1. Configure resources to send all diagnostic logs to a Log Analytics workspace
2. Deploy Azure Optimization engine to the same Log Analytics workspace
3. Wait 24 hours
4. Go to the same LA workspace -> Workbooks -> click on Reservations Potential
5. Click on any line in the "On-demand sizes usage and RI potential/fragmentation" table
6. Receive error

## 🤔 Expected
The Estimated Commitment and Savings section gives details on estimated commitments and savings

## 📷 Screenshots
![image](https://github.com/user-attachments/assets/137f52dc-e53e-4594-9562-791730b7e3f0)

## ℹ️ Additional context
This is a standard pay-as-you-go MCA tenant and subscription.

## 🙋‍♀️ Ask for the community
We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by helderpinto** [comment]
Thank you for reporting this, @MohnJadden. This workbook depends on the `AzureOptimizationPricesheetV1_CL` Log Analytics table to be populated by the `Export-PriceSheetToBlobStorage` runbook.

Please check whether the aforementioned runbook is generating any exception. It might be a case of lack of permissions by the AOE managed identity at the MCA level. Please, follow the steps described [here](https://aka.ms/AzureOptimizationEngine/commitmentssetup) to assign the required permissions to AOE.

**Comment by helderpinto** [comment]
Hi, @MohnJadden. Can you please confirm whether you were able to solve the issue?

**Comment by MohnJadden** [comment]
Confirmed, the dependency Powershell script fixed the issue.  Thanks for checking in!
