### ISSUE TITLE
FinOps Governance Workbook - Not allowing to select subscriptions from the dropdown

### ISSUE THREAD

**Issue by saikovvuri** [microsoft/finops-toolkit#852]
## 🐛 Problem
Governance Workbook is not displaying subscriptions to select 

## 👣 Repro steps
TODO: Add repro steps below:
Deploy workbook from https://microsoft.github.io/finops-toolkit/governance-workbook
Go to azure monitor / workbooks
Click on Governance workbook

## 🤔 Expected
TODO: Add a clear and concise description of what you expected to happen.

## 📷 Screenshots
![image](https://github.com/user-attachments/assets/52ac9849-2752-41d3-a0c2-6e5578503f38)

## ℹ️ Additional context
TODO: Add any other context about the problem here. Remove if not applicable.

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by arthurclares** [comment]
This workbook requires a management group to be selected before it can pull up the list of respective subscriptions. I'm assigning this to @nteyan to improve the subscription query to work with or without a management group selected or to document this requirement.
