### ISSUE TITLE
Setting up FinOps-Hub Rate Optimization Dashboard

### ISSUE THREAD

**Issue by Zeo-shark** [microsoft/finops-toolkit#854]
## ⚠️ Problem
Need help with setting up the Rate Optimization Power BI Dashboard. This issue occurs repeatedly when I provide my storage URL, scope, enrollment number, and start/end date range. On the next tab, it asks for the Account Key, but the storage account URL in the drop-down defaults to the storage blob URL, which cannot be removed. This results in the error: “InstanceSizeFlexibility: Credentials are required to connect to the blob.”

![image](https://github.com/user-attachments/assets/edbd4cd9-0021-4933-80e0-c8a0f9bf6d5c)
![image](https://github.com/user-attachments/assets/2da970e5-95f2-48f6-a625-c0cab9ba0373)

## 🛠️ Solution
You should select  "Anonymous" for the CCM storage account. You should see your storage account in the next screen. This dashboard connects to two different storage accounts: First it connects to the CCM storage account to grab information about the Instance Flexbilkity Group for RI, and then it connects to your storage account to grab the billing data. 
You don't need authentication for the first one. Only for the second one.

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by arthurclares** [comment]
@Zeo-shark thank you for flagging this. 
You should select  "Anonymous" for the CCM storage account. You should see your SA in the next screen.
This dashboard connects to two different storage accounts: First it connects to the CCM storage account to grab information about the Instance Flexibility Group for RI, and then it connects to your storage account to grab the billing data. 
You don't need authentication for the first one. Only for the second one.
