### ISSUE TITLE
[Power BI] Add docs for how to use SAS tokens

### ISSUE THREAD

**Issue by flanakin** [microsoft/finops-toolkit#859]
## ⚠️ Problem
There's no assistance for configuring Power BI reports to use a SAS token.

## 🛠️ Solution
Document the steps needed to use SAS tokens with Power BI reports.

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by Zeo-shark** [comment]
Hello @flanakin can you please assign this to me
