### ISSUE TITLE
Link is broken 

### ISSUE THREAD

**Issue by dbabumunichre** [microsoft/finops-toolkit#881]
## 🐛 Problem
The link is not working, getting 404 error.

## 👣 Repro steps
Visit this link:
https://microsoft.github.io/finops-toolkit/hubs/reports/README.md

**Comment by arthurclares** [comment]
@dbabumunichre Where is this link being referenced?

**Comment by Misba-Yousuf** [comment]
This part of the link is broken **If you run into any issues, see [Troubleshooting Power BI reports](https://microsoft.github.io/resources/troubleshooting.md).** 
https://microsoft.github.io/resources/troubleshooting.md ----- page is unavailable
