### ISSUE TITLE
ADF pipeline config_ExportData ForEach Export Scope | Failed | ForEach

### ISSUE THREAD

**Issue by saleemmy** [microsoft/finops-toolkit#885]
Getting this error in the ADF pipeline config_ExportData

ForEach Export Scope | Failed | ForEach | 8/8/2024, 2:25:43 PM | 2s

Error details
ForEach Export Scope
Error code
[InvalidTemplate](https://go.microsoft.com/fwlink/?linkid=2112593#error-code-invalidtemplate)
Failure type
User configuration issue
Details
The function 'length' expects its parameter to be an array or a string. The provided value is of type 'Object'.
Activity ID
d803c837-a781-471f-b1ba-90034e3f28f4
Error source
Pipeline
config_ExportData

**Comment by MSBrett** [comment]
Unless you're using managed exports you can safely ignore that error.  

If you've configured the cost management exports manually and you want to suppress the error entirely you can disable the config_DailySchedule and config_MonthlySchedule triggers in ADF.

**Comment by CollinsNasongo** [comment]
Operation on target ForEach Export Scope failed: Activity failed because an inner activity failed; Inner activity name: Create or update open month focus export, Error: {"error":{"code":"400","message":"The remote server returned an error: (400) Bad Request.
