### ISSUE TITLE
Cost optimization v0.4 workbook - Reservation section fails to load

### ISSUE THREAD

**Issue by psilantropy** [microsoft/finops-toolkit#902]
## 🐛 Problem
Cost Optimization v.03 and v.04 bug with resource type not found.

## 👣 Repro steps
Open v.03 or v.04 cost opt workbook.
Rate optimization
Azure reservations
First load "no reservations recommendations found" < typo there too.
Change term or anything else, auto refresh.
```
This query could not run because some parameters are not set.
Please set: Resource type
```
Resource type never has anything other than "All"

## 📷 Screenshots

![image](https://github.com/user-attachments/assets/397d6deb-7399-4b59-afbf-20f7ebd4c063)

![image](https://github.com/user-attachments/assets/5801f987-5baa-4b46-bf96-aa63af53421b)

![image](https://github.com/user-attachments/assets/668df4a8-3a8b-43bd-be43-350e80f2d7a3)

Everything else seems to function ok.
Savings plan rec is 'no recommendations found'. We do have a high utilisation savings plan, but I thought i'd get a rec at 3y. Not sure.
This is an EA account.

**Comment by arthurclares** [comment]
@psilantropy The first issue is already fixed on the version that we will release later this month. 
About the savings plan issue, do you see any recommendations on Advisor? 
This workbook tab copies the data from Advisor, so if you don't have any recommendations there, you won't see anything on the workbook either. 
The break even point is the only calculation we are doing in the workbook. Everything else comes straight from Advisor via Azure Resource Graph queries.

**Comment by psilantropy** [comment]
> @psilantropy The first issue is already fixed on the version that we will release later this month. About the savings plan issue, do you see any recommendations on Advisor? This workbook tab copies the data from Advisor, so if you don't have any recommendations there, you won't see anything on the workbook either. The break even point is the only calculation we are doing in the workbook. Everything else comes straight from Advisor via Azure Resource Graph queries.

Great, thank you.
Savings plan: Yes it looks like you are right, thanks for the information.
