### ISSUE TITLE
[Hubs] ETL ingestion pipeline failed with timeout

### ISSUE THREAD

**Issue by saleemmy** [microsoft/finops-toolkit#905]
Hi
I am getting the ETL ingestion pipeline failed due to time out. Has anyone encountered this. appreciate some help to resolve this. 

msexports_ETL_ingestion | 8/14/2024, 12:11:27 PM | 8/14/2024, 12:16:47 PM | 5m 21s | a0c2ca55-2d83-4337-aa65-a1eb054a1efc | Failed | 
msexports_ETL_ingestion | 8/14/2024, 12:11:27 PM | 8/14/2024, 12:16:56 PM | 5m 29s | bdada97a-3d0f-4e87-ae3b-86be9bddf5b1 | Failed | Original |

**Comment by flanakin** [comment]
@saleemmy can you share the error details?

**Comment by jamelachahbar** [comment]
@saleemmy do you still need assistance with this? I'll be happy to go through it with you and help resolve it.

Thanks!

**Comment by saleemmy** [comment]
Thanks. it is resolved.
