### ISSUE TITLE
Services Retirement APIM rule showing resources not affected.

### ISSUE THREAD

**Issue by wwmurphyAB** [microsoft/finops-toolkit#913]
## 🐛 Problem
APIM Compute Platform (stv1) rule in Services Retirement reporting incorrect resources.

## 👣 Repro steps
1. Have API Management service that uses Consumption sku, mtv1.
2. Go to the Governance Workbook
3. Choose the Services retirement tab
4. ensure the filter settings include the subscription, resource group, and location for the APIM instance from Step 1.
5. Select the retiring service "API Management Compute Platform (stv1)" from the list.

## 🤔 Expected
Only show API Management resources running on compute "stv1" should not include instances running on "mtv1"

## 📷 Screenshots
![image](https://github.com/user-attachments/assets/895db1e1-d024-45f5-a4c3-5144b8e6a753)
![image](https://github.com/user-attachments/assets/fc465733-75f8-4fd3-861b-7680e04f0861)

**Comment by flanakin** [comment]
@allcontributors Please add wwmurphyAB for bugs

**Comment by nteyan** [comment]
@wwmurphyAB, thank you for bringing this to our attention and apologies for the delayed response. This section of the governance workbook is connected to the AzureServiceRetirement community workbook:
![image](https://github.com/user-attachments/assets/8d2e54e3-bad5-42cb-87a2-d8f8c4841328)
 For support, you can either open a bug report here: https://github.com/microsoft/Application-Insights-Workbooks/blob/master/Workbooks/Azure%20Advisor/AzureServiceRetirement/Azure%20Services%20Retirement.workbook or create a support request through the Azure Portal.
