### ISSUE TITLE
[Power BI] Eligible for AHB Windows Servers are Not Detected if licensetype is null or if the SQL server doesn't list Windows  

### ISSUE THREAD

**Issue by da5is** [microsoft/finops-toolkit#938]
## 🐛 Problem

In cases where a Windows Virtual Machine is deployed and licenseType is set null or Windows SQL servers indicate SQL but not Windows (such as potential ws2012 deployments), the AHB report does not show these VMs as eligible but not covered by AHB. 

_Verbatim customer comment:  " I can see we are being charged for Windows Server Licenses, but they don’t have the License_Type = Windows_Server. I believe this is happening for two reasons, either we didn’t enter any “Source image details” or the details indicate “SQL” but the OS is “Windows”."_

## 👣 Repro steps

Deploy VMs uncovered by AHB that meet these criteria - they will not show up as potential AHB candidates in the workbook.

## ℹ️ Additional context

I believe this is related to lines 125 and 159 where we're checking for Windows in licenseType explicitly, which doesn't detect instances where licenseType is null or Windows isn't the explicit string (such as ws2012).

**Comment by flanakin** [comment]
Added this to the list for the September release for investigation. 

@BenShy, if you have any context, that might help us determine the right fix.

**Comment by flanakin** [comment]
@allcontributors Please add da5is for bug

**Comment by arthurclares** [comment]
@flanakin This is for the workbook. I'm taking it.

**Comment by arthurclares** [comment]
@flanakin This is for the workbook. Seif and I have been in touch with @da5is already.

**Comment by arthurclares** [comment]
This is fixed and will be shipped with the next release (0.6)
