### ISSUE TITLE
Error during the deploy

### ISSUE THREAD

**Issue by fbcarvalho** [microsoft/finops-toolkit#941]
Hello everyone!

I'm trying to deploy the AOE and I'm receiving this error. I've tried the deployment many times but it didn't work.

Any suggestion?

![image](https://github.com/user-attachments/assets/0b6bde49-30d8-44b1-9025-431074acb648)

**Comment by helderpinto** [comment]
Thank you for reporting this issue, @fbcarvalho. Can you please share more details about the template deployment failure? You can find more details by looking at the `resourcesDeployment` deployment in the `aoebbb-rg` resource group deployments. 

<img width="514" alt="image" src="https://github.com/user-attachments/assets/4abd797f-bc8f-4b4d-b8a9-8fc84308ffff">

If everything went fine at the resource group level, check also the Subscription deployments. If the error details link doesn't help, try looking at the "Related Events" link.

<img width="926" alt="image" src="https://github.com/user-attachments/assets/b90f9a9e-2876-4082-b589-5a649f995624">

**Comment by fbcarvalho** [comment]
Thanks Elder.

There was a policy blocking my deployment at subscription level. I was looking for deployment errors at resource group level and I couldn't identify the error.  

Thank you!
