### ISSUE TITLE
Update the FOCUS dataset example

### ISSUE THREAD

**Issue by tiagobalabuch** [microsoft/finops-toolkit#955]
## ⚠️ Problem
FOCUS dataset example available is labeled as (1.0-preview(v1)) and doesn't reflect the changes made recently. 
The latest version of FOCUS introduces additional columns and removes others.

## 🛠️ Solution
Update the dataset to reflect the latest FOCUS version

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by flanakin** [comment]
@tiagobalabuch We actually have 2 datasets. We have 1.0 and 1.0-preview. Where are you seeing only the preview dataset?
![Screenshot of the 2 FOCUS dataset examples](https://github.com/user-attachments/assets/b3430fb3-c83e-4529-9d3d-737a1f355578)

#needs-info

**Comment by flanakin** [comment]
I see we don't mention we have FOCUS 1.0 data on the [open data doc](https://microsoft.github.io/finops-toolkit/data#%EF%B8%8F-dataset-examples). Is that where you saw this?
![Screenshot of the Open data doc](https://github.com/user-attachments/assets/f1e53911-cdf4-4259-9b0b-5ecef847c203)

**Comment by arthurclares** [comment]
Confirmed with the requestor that this is now working.
