### ISSUE TITLE
[Power BI] Document how to test/demo Power BI reports via PBI Desktop

### ISSUE THREAD

**Issue by flanakin** [microsoft/finops-toolkit#958]
## ⚠️ Problem
The FinOps toolkit doesn't have a public demo environment today but the Power BI reports can be demo'ed by using Power BI Desktop since the sample reports include test data.

## 🛠️ Solution
Document the fact that people can test or demo Power BI reports by simply installing Power BI Desktop on a Windows machine.

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by Zeo-shark** [comment]
@flanakin can you please assign this issue to me.
