### ISSUE TITLE
FinOps Hub - Solution Cost change between v4 and v5 with introduction of namespace resource type.

### ISSUE THREAD

**Issue by psilantropy** [microsoft/finops-toolkit#962]
Hi,

Trying to find some reference to this. But the namespaces resource was introduced and turned this from an almost free solution to a daily cost exceeding the previous cost _significantly_.

Eventgrid namespace, and meter = standard throughput unit.

Obviously not a huge charge. But it is $0.05 NZD in v4 vs $1.60 NZD a day in v5. Enough to add to the release notes considering this is finops? ;) 

Thanks.

Edit: Correction, was a v3 to v4 upgrade. I'll deploy v5 shortly anyway.

**Comment by flanakin** [comment]
Oh, wow... We'll remove this for the September release. It was supposed to be deleted during the deployment. Please delete the resource in the meantime.

**Comment by psilantropy** [comment]
> Oh, wow... We'll remove this for the September release. It was supposed to be deleted during the deployment. Please delete the resource in the meantime.

It looks like the v4 to v5 update deleted it.

**Comment by arthurclares** [comment]
@flanakin have you changed this for v06? Are we good to keep this for September?
