### ISSUE TITLE
Ingestion issues - duplicate data - strange results in PowerBI reports

### ISSUE THREAD

**Issue by psilantropy** [microsoft/finops-toolkit#966]
## 🐛 Problem
I've deployed FinOps hub a few times. I think going from 0.2 to .0.3 RC, then 0.3 0.4 and now 0.5. 

When I look at my reports I have some strange data that must be the result of bad imports into the storage account. Wondering if this is a hole I can dig myself out of - but really I could just wipe the entire setup and redeploy.

It would be nice to retain my original historical imports, as I think this data would be lost due to age?

## 👣 Repro steps

I have these cost exports which I created back in February with 1.0-preview(v1).

![image](https://github.com/user-attachments/assets/6b3ad93d-b27a-49b8-b8ca-8e26bd3a40d8)

My main daily FinOpsHubMonthtodate export

![image](https://github.com/user-attachments/assets/6e987f3d-d844-4b67-a870-e598a010252c)

msexports storage account

![image](https://github.com/user-attachments/assets/8e8f525b-f508-4dc1-bb8f-f6fb0cef55db)

 msexports/account/ - Duplicate data or ok?

![image](https://github.com/user-attachments/assets/408592eb-292c-4c9d-9809-8cb14274ddd0) 
![image](https://github.com/user-attachments/assets/e8e5dc50-cce5-4f57-ae34-193c834d6362)

Data factory triggers
![image](https://github.com/user-attachments/assets/4a69e4bc-215a-42e6-8799-314d45d26056)

Data factory linked services (deploy failed to clean up??)

![image](https://github.com/user-attachments/assets/5b588bda-61ff-4e2a-a6ca-e1a124163db9)

Pipelines

![image](https://github.com/user-attachments/assets/909ce8cc-bd88-4c44-9c28-6693087e76f8)

## 🤔 Expected

Probably not worth the time digging this detail up for screenshots but I have very inaccurate cost details vs Azure Cost Analysis. Some months look ok, some look way too high.

My ingestion powerbi report had strange details, but now on 0.5 it doesn't work at all. Keeps all the 'demo data'.

**Comment by flanakin** [comment]
@psilantropy You shouldn't see any duplication as of 0.4, which changed to use the manifest for identifying export scopes. To confirm, you'd need to look at the parquet files in the `ingestion` container. If you see any folders that duplicate other folders, then that will cause data duplication because the pipelines copy to a destination folder. I suspect the cases where you might be seeing that are from before 0.4 because of how we identified scopes based on the export path.

The easiest way to fix that is obviously to clear the ingestion container and re-export data for up to the last 7 years via the Start-FinOpsCostExport PowerShell command. That said, you shouldn't need to do that.

I'm not sure if we have a way to identify duplication cleanly, but we can definitely put some thought into it. I could see that going into the Data ingestion report to facilitate troubleshooting like this.

**Comment by psilantropy** [comment]
Hi @flanakin, thanks for the information and advice.

![image](https://github.com/user-attachments/assets/826379ea-55aa-46d6-b6a0-18df5e05c121)

My inactive (single use exports) exports look ilke this;
![image](https://github.com/user-attachments/assets/56050ab9-3376-4d53-b86b-237924d0821a)

My month to date export, untouched since Feb-24

Good feb
![image](https://github.com/user-attachments/assets/c8debf1c-e529-429a-a2d0-48e171eae16c)

March ok with 2 files?

![image](https://github.com/user-attachments/assets/e98559fa-adb3-4b39-ad2f-843d98088ff9)

![image](https://github.com/user-attachments/assets/26903f7f-b7a2-4637-9af8-187d275d97ec)

All folders up to August look like this with 2x parquet files.

Then a new folder structure as per the below;

August (again)
![image](https://github.com/user-attachments/assets/d110a496-fdc5-49e0-b375-4cc293a97ae6)

September
![image](https://github.com/user-attachments/assets/f8b7dcea-8323-419b-a400-b4072321195b)


Honestly I don't care if I have to export again to get this clean. So delete these two folders?

![image](https://github.com/user-attachments/assets/b21dd476-e8d8-49ec-a6df-995aa4fa5703)

Delete/stop my cost exports job? (finopshubmonthtodate)

Then run ?

`Start-FinopsCostExport -Name 'CostExport' -Backfill 24`

**Comment by flanakin** [comment]
@psilantropy Those very short paths look suspicious, but it's hard to say without seeing the values. Let's setup some time so we can look at them together. Can you email ftk-support@ms so we can setup some time?

**Comment by psilantropy** [comment]
Happy to do that, but only if you gain something from reviewing it. More than happy to wipe it out.

**Comment by flanakin** [comment]
Short answer: Keep "providers" and delete the other, then backfill 1 export. Don't forget to set the correct export name and specify the scope of the billing account in the command call:
`Start-FinOpsCostExport -Name 'finopshubmonthtodate' -Scope '/providers/Microsoft.Billing/billingAccounts/###' -Backfill 24`


Long answer...

I'm assuming you only have one billing account. If that's true, then you should only see one path to parquet files in the ingestion container:
`providers/microsoft.billing/billingaccounts/###/focuscost/yyyyMM/*.parquet`

If you have any others, check the months to make sure you don't have duplicate months. If you do, delete the other folder and keep the one at the path above.

The one other thing I'm noticing in your files that seems odd is that you seem to have one parquet file created on the first and another created later in the month. That seems suspicious. Without confirming, I almost wonder if there's a different file naming pattern for daily vs. monthly exports, which could be causing 2 versions of the file to be created. Hubs overwrites files based on name and would miss this case if the same file had a new name, which would definitely result in duplicated files. But that's just a guess at this point...

**Comment by psilantropy** [comment]
I just wiped it all. Had some issues importing after the delete.
Ingestion report looks ok now. Folder structure clean.
CostSummary report looks good.
Commitment reports has a null value error, but i'll review and log after reviewing the cost summary in detail. 

Appreciate your assistance.
