### ISSUE TITLE
[Power BI] Setup doc has broken markup

### ISSUE THREAD

**Issue by flanakin** [microsoft/finops-toolkit#968]
## ⚠️ Problem
[Power BI setup doc](https://microsoft.github.io/finops-toolkit/power-bi/setup) has broken markup.
![Screenshot of the PBI setup doc where the markup isn't formatted correctly](https://github.com/user-attachments/assets/b9816c8b-4682-45c0-8e5f-41a7f4b61f78)

## 🛠️ Solution
Fix the markup 😜

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by Zeo-shark** [comment]
@flanakin can you please assign this to me.
