### ISSUE TITLE
Commitment savings are 0 for a specific month only even after re-exporting the data

### ISSUE THREAD

**Issue by kasimrehman** [microsoft/finops-toolkit#977]
## 🐛 Problem
There are some open issues regarding commitment savings but this one looks more like one that was closed. A customer's Summary in Cost Summary PowerBI app is showing commitment savings a 0 for the month of June. The data for June has been re-exported to the corresponding storage account yesterday (again), with the option set to overwrite data, but the data still shows no commitment savings for June. Please have a look at the attached screenshot. On the Commitments page we see 100% unused discounts for June, 0% unused for July, and in August the effective costs shoots up only to come down to the July level in September. 

The data format is FOCUS 1.0. The data factory pipelines are run through ok for the re-export of the June data.

## 👣 Repro steps
TODO: Add repro steps below:
1. Go to Cost Summary PowerBI App
2. Click Summary page for the line graph, and the Commitments page for the bar graph
3. Examine the graphs

## 🤔 Expected
Commitment savings should not be 0 in June after re-exporting the newest data.

## 📷 Screenshots
![image](https://github.com/user-attachments/assets/a3bc042c-beda-4576-8c7b-43e0d23d2b98)
![image](https://github.com/user-attachments/assets/aa4e4596-bae4-4ab7-9982-c74c16124553)
![image](https://github.com/user-attachments/assets/c589caf9-c661-4730-a71c-e610a65b8f62)
![image](https://github.com/user-attachments/assets/1b3381a5-5385-4342-bdc2-e3f76f0ef409)

**Comment by flanakin** [comment]
@kasimrehman Can you email ftk-support@ms with some times you'd be able to meet to troubleshoot on a call? I think we'll need a little more detail to get to the bottom of this.

**Comment by kasimrehman** [comment]
Hi Mike, Thank you for your proposal. My customer contact has gone on vacation but as soon as they are back I will schedule this.
