### ISSUE TITLE
Incremental refresh with private end point

### ISSUE THREAD

**Issue by saleemmy** [microsoft/finops-toolkit#986]
Looking for advise on enabling incremental refresh in powerbi desktop with private end point.

**Comment by arthurclares** [comment]
@l-vijayaraghavan

**Comment by arthurclares** [comment]
@MSBrett Can you help with this?

**Comment by flanakin** [comment]
I believe there's an issue with a change in Azure Data Factory parquet file generation. We have some fixes coming in 0.6 that should help with that. Not sure if that's what you're getting hit by. @MSBrett can share more details, if needed.

**Comment by MSBrett** [comment]
0.6 has the required changes for Incremental Refresh to work reliably.  

Private Endpoint support would also require deploying a PBI data gateway onto the same vNet as the data lake.  We don't do this during deployment yet.
