### ISSUE TITLE
Managed Identity not created when deploying

### ISSUE THREAD

**Issue by guidovanbrakel** [microsoft/finops-toolkit#992]
For some reason the managed identity is not created when I tried, I'm very new to this, please help me troubleshoot the issue. This regarding the optimization engine

**Comment by helderpinto** [comment]
Hi, @guidovanbrakel. What do you mean by the managed identity not being created? Actually, by default, the AOE MI is not a user-assigned MI - it is a system-assigned MI, that is assigned to the AOE automation account during deployment. If you open the Identity section of the AOE automation account, you'll normally see it enabled there.

**Comment by guidovanbrakel** [comment]
Fixed

**Comment by guidovanbrakel** [comment]
Fixed
