### ISSUE TITLE
In Rate Optimization PowerBI, we do see the savings for Saving Plan but not for Reservations

### ISSUE THREAD

**Issue by josesarsa** [microsoft/finops-toolkit#997]
## 🐛 Problem
TODO: In Rate Optimization PowerBI, we do see the savings for Saving Plan but not for Reservations

## 👣 Repro steps
TODO: When you click in Rate Optimization PowerBI in Savings, the Reservations give you 0 savings whereas Saving Plans provides you the right amount

## 🤔 Expected
TODO: We need the Reservation Savings for the contract and for the commitments

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by josesarsa** [comment]
This is an example of what we see for a reservation. Saving Plans are fine

![image](https://github.com/user-attachments/assets/582556c0-e352-4390-b01c-607d9902f0d7)

**Comment by josesarsa** [comment]
It is an MCA contract

**Comment by flanakin** [comment]
This is not a bug. This is a gap in Cost Management data where it does not include contracted (on-demand) cost.

We are planning to join the cost and price data as a workaround.

**Comment by josesarsa** [comment]
in version 0.6?

**Comment by flanakin** [comment]
We have added a workaround for MCA account savings calculation in Azure Data Explorer data ingestion. Stay tuned for the 0.7 release.
