### ISSUE TITLE
An error occurred in the ‘ftk_LoadData’ query. Expression.Error: We cannot convert the value null to type Table. Details:     Value=     Type=[Type]

### ISSUE THREAD

**Issue by highsmithjd** [microsoft/finops-toolkit#999]
I've set up the FinOps Hub. Data is in the ingestion container as a parquet file. I can access the data with the cost summary report so permissions are fine and the data looks good. When i try and use the FOCUS report i get the following error:

An error occurred in the ‘ftk_LoadData’ query. Expression.Error: We cannot convert the value null to type Table.
Details:
    Value=
    Type=[Type]

I've seen a previous issue in GitHub and nothing seemed to fix my problem. Any help is much appreciated. Thanks!

**Comment by JAK1047** [comment]
Same issue only in the RateOptimization report. The CostSummary one works fine.

**Comment by arthurclares** [comment]
@highsmithjd What's the Hub and Report version that you are running? You can check the Hubs version by looking at the settings.json inside of the config container.
To check the report version, just open it on PBI desktop and look at the "Get Started" page. There is a little "version" at the top
![image](https://github.com/user-attachments/assets/56f0449c-b39e-4e4d-9830-4af6d3d56c60)

**Comment by highsmithjd** [comment]
Microsoft support said the FOCUS report does not work with FinOps 2.0 or greater. The FOCUS report is merged into the Cost Summary report.
